(** * C1542_MorVlambdaOrbit: Moreno (1997) Theorem 1.16 -- abstract orbit/module lane.

    Moreno's proof of Theorem 1.16 is structural: for lambda > 0, each
    eigenspace V_lambda carries a quaternionic orbit structure generated by
    the H_a action, so dim_R V_lambda is divisible by 4.

    In this repo the finite-dimensional H-module dimension theorem already
    lives in HModuleDim.v / FinDimHModule.v.  This file packages that result
    as the paper-scoped abstract Moreno lane:

    - if V_lambda is presented as a finite-dimensional right H-module, then
      dim_R V_lambda = 4k
    - equivalently, dim_R V_lambda = 0 mod 4

    The remaining open bridge is to instantiate these module hypotheses from
    the concrete Cayley-Dickson subspace V_lambda inside H_a^perp for an
    arbitrary doubly-pure unit-norm a.  The canonical A_3 witness lives in
    C1542_MorVlambdaMod4.v. *)

From Stdlib Require Import Reals Arith PeanoNat Lia.
From OpenGororoba Require Import Prelude CayleyDicksonAlgebra Sedenion OctonionNorm FinDimHModule HModuleDim.
From OpenGororoba Require Import C1540_MorHaQuaternion.

Open Scope R_scope.
Open Scope nat_scope.

Module Type MorenoVlambdaModule.
  Include HModuleFinDim.
  Parameter lambda : R.
  Axiom lambda_pos : (0 < lambda)%R.
End MorenoVlambdaModule.

Module MorenoVlambdaDim (M : MorenoVlambdaModule).
  Module Import Dim := HModDimThm M.

  Theorem moreno16_vlambda_dim_div4 :
    exists k : nat, M.v_dim = 4 * k.
  Proof.
    exact h_module_dim_div4.
  Qed.

  Corollary moreno16_vlambda_dim_mod4 :
    Nat.modulo M.v_dim 4 = 0.
  Proof.
    destruct moreno16_vlambda_dim_div4 as [k Hk].
    rewrite Hk.
    rewrite Nat.mul_comm.
    apply Nat.Div0.mod_mul.
  Qed.
End MorenoVlambdaDim.

Section Moreno16OrbitPredicate.
  Variable vl_dim : nat.
  Hypothesis Hvl_dim : is_h_module_dim vl_dim.

  Theorem moreno16_orbit_dim_div4 :
    exists k : nat, vl_dim = 4 * k.
  Proof.
    exact (FinDimHModule.h_module_dim_div4 vl_dim Hvl_dim).
  Qed.

  Corollary moreno16_orbit_dim_mod4 :
    Nat.modulo vl_dim 4 = 0.
  Proof.
    destruct moreno16_orbit_dim_div4 as [k Hk].
    rewrite Hk.
    rewrite Nat.mul_comm.
    apply Nat.Div0.mod_mul.
  Qed.
End Moreno16OrbitPredicate.

Example moreno16_hmd_4 :
  is_h_module_dim 4.
Proof.
  apply hmd_step; [lia | exact hmd_zero].
Qed.

Example moreno16_hmd_8 :
  is_h_module_dim 8.
Proof.
  apply hmd_step; [lia | exact moreno16_hmd_4].
Qed.

Example moreno16_example_dim4 :
  exists k : nat, 4 = 4 * k.
Proof.
  exact (moreno16_orbit_dim_div4 4 moreno16_hmd_4).
Qed.

Example moreno16_example_dim8 :
  Nat.modulo 8 4 = 0.
Proof.
  exact (moreno16_orbit_dim_mod4 8 moreno16_hmd_8).
Qed.

Record Moreno16ConcreteVlambdaWitness := {
  moreno16_concrete_lambda : R;
  moreno16_concrete_lambda_pos : (0 < moreno16_concrete_lambda)%R;
  moreno16_concrete_vlambda_dim : nat;
  moreno16_concrete_vlambda_is_h_module_dim :
    is_h_module_dim moreno16_concrete_vlambda_dim
}.

Record Moreno16ArbitraryAConcreteHypotheses := {
  moreno16_concrete_a : CDOct;
  moreno16_concrete_a_unit : oct_norm_sq moreno16_concrete_a = 1%R;
  moreno16_concrete_a_pure : oct_conj moreno16_concrete_a = oct_neg moreno16_concrete_a;
  moreno16_concrete_witness : Moreno16ConcreteVlambdaWitness
}.

Record Moreno16ArbitraryAVlambdaWitness := {
  moreno16_arbitrary_a : CDOct;
  moreno16_arbitrary_a_unit : oct_norm_sq moreno16_arbitrary_a = 1%R;
  moreno16_arbitrary_a_pure :
    oct_conj moreno16_arbitrary_a = oct_neg moreno16_arbitrary_a;
  moreno16_arbitrary_lambda : R;
  moreno16_arbitrary_lambda_pos : (0 < moreno16_arbitrary_lambda)%R;
  moreno16_arbitrary_vlambda_dim : nat;
  moreno16_arbitrary_vlambda_is_h_module_dim :
    is_h_module_dim moreno16_arbitrary_vlambda_dim
}.

Record Moreno16ArbitraryAConcreteVlambdaHypotheses := {
  moreno16_concrete_hyp_a : CDOct;
  moreno16_concrete_hyp_a_unit : oct_norm_sq moreno16_concrete_hyp_a = 1%R;
  moreno16_concrete_hyp_a_pure :
    oct_conj moreno16_concrete_hyp_a = oct_neg moreno16_concrete_hyp_a;
  moreno16_concrete_hyp_lambda : R;
  moreno16_concrete_hyp_lambda_pos : (0 < moreno16_concrete_hyp_lambda)%R;
  moreno16_concrete_hyp_vlambda_dim : nat;
  moreno16_concrete_hyp_vlambda_is_h_module_dim :
    is_h_module_dim moreno16_concrete_hyp_vlambda_dim
}.

(** A first geometry-shaped arbitrary-a package.

    Instead of assuming `is_h_module_dim` directly, this package records the
    concrete dimensional shadow of Moreno's geometric claim: V_lambda(a)
    decomposes into a finite number of quaternionic 4-blocks.  From that block
    count we derive both the H-module-dimension predicate and the mod-4
    conclusion.  This is still weaker than a full formalization of the
    subspace geometry, but it is closer to Moreno's actual proof shape than
    the earlier witness-only package. *)
Record Moreno16ArbitraryAGeometricVlambdaData := {
  moreno16_geom_a : CDOct;
  moreno16_geom_a_unit : oct_norm_sq moreno16_geom_a = 1%R;
  moreno16_geom_a_pure :
    oct_conj moreno16_geom_a = oct_neg moreno16_geom_a;
  moreno16_geom_lambda : R;
  moreno16_geom_lambda_pos : (0 < moreno16_geom_lambda)%R;
  moreno16_geom_vlambda_dim : nat;
  moreno16_geom_block_count : nat;
  moreno16_geom_vlambda_dim_is_blocks :
    moreno16_geom_vlambda_dim = 4 * moreno16_geom_block_count
}.

Theorem moreno16_geometry_is_h_module_dim :
  forall G : Moreno16ArbitraryAGeometricVlambdaData,
    is_h_module_dim (moreno16_geom_vlambda_dim G).
Proof.
  intro G.
  rewrite (moreno16_geom_vlambda_dim_is_blocks G).
  exact (div4_implies_h_module_dim (moreno16_geom_block_count G)).
Qed.

Theorem moreno16_concrete_witness_dim_div4 :
  forall W : Moreno16ConcreteVlambdaWitness,
    exists k : nat, moreno16_concrete_vlambda_dim W = 4 * k.
Proof.
  intro W.
  exact (FinDimHModule.h_module_dim_div4
           (moreno16_concrete_vlambda_dim W)
           (moreno16_concrete_vlambda_is_h_module_dim W)).
Qed.

Corollary moreno16_concrete_witness_dim_mod4 :
  forall W : Moreno16ConcreteVlambdaWitness,
    Nat.modulo (moreno16_concrete_vlambda_dim W) 4 = 0.
Proof.
  intro W.
  destruct (moreno16_concrete_witness_dim_div4 W) as [k Hk].
  rewrite Hk.
  rewrite Nat.mul_comm.
  apply Nat.Div0.mod_mul.
Qed.

Theorem moreno16_arbitrary_a_dim_div4 :
  forall H : Moreno16ArbitraryAConcreteHypotheses,
    exists k : nat,
      moreno16_concrete_vlambda_dim (moreno16_concrete_witness H) = 4 * k.
Proof.
  intro H.
  exact (moreno16_concrete_witness_dim_div4 (moreno16_concrete_witness H)).
Qed.

Corollary moreno16_arbitrary_a_dim_mod4 :
  forall H : Moreno16ArbitraryAConcreteHypotheses,
    Nat.modulo (moreno16_concrete_vlambda_dim (moreno16_concrete_witness H)) 4 = 0.
Proof.
  intro H.
  exact (moreno16_concrete_witness_dim_mod4 (moreno16_concrete_witness H)).
Qed.

Definition moreno16_canonical_vlambda_witness : Moreno16ConcreteVlambdaWitness.
Proof.
  refine {| moreno16_concrete_lambda := 1%R;
            moreno16_concrete_lambda_pos := Rlt_0_1;
            moreno16_concrete_vlambda_dim := 4%nat;
            moreno16_concrete_vlambda_is_h_module_dim := moreno16_hmd_4 |}.
Defined.

Lemma moreno16_canonical_a_unit :
  oct_norm_sq moreno_a = 1%R.
Proof.
  unfold moreno_a.
  apply oct_basis_unit_norm.
  lia.
Qed.

Lemma moreno16_canonical_a_pure :
  oct_conj moreno_a = oct_neg moreno_a.
Proof.
  unfold moreno_a.
  cbv [oct_conj oct_neg oct_e oct_lo oct_hi
       quat_conj quat_neg quat_zero quat_one qa qb qc qd].
  apply (f_equal2 mkOct); apply (f_equal4 mkQuat); ring.
Qed.

Definition moreno16_canonical_arbitrary_a_hypotheses :
  Moreno16ArbitraryAConcreteHypotheses.
Proof.
  refine {| moreno16_concrete_a := moreno_a;
            moreno16_concrete_a_unit := moreno16_canonical_a_unit;
            moreno16_concrete_a_pure := moreno16_canonical_a_pure;
            moreno16_concrete_witness := moreno16_canonical_vlambda_witness |}.
Defined.

Definition moreno16_build_arbitrary_a_concrete_hypotheses
  (a : CDOct)
  (Ha_unit : oct_norm_sq a = 1%R)
  (Ha_pure : oct_conj a = oct_neg a)
  (W : Moreno16ConcreteVlambdaWitness)
  : Moreno16ArbitraryAConcreteHypotheses :=
  {| moreno16_concrete_a := a;
     moreno16_concrete_a_unit := Ha_unit;
     moreno16_concrete_a_pure := Ha_pure;
     moreno16_concrete_witness := W |}.

Definition moreno16_arbitrary_witness_to_concrete
  (W : Moreno16ArbitraryAVlambdaWitness)
  : Moreno16ConcreteVlambdaWitness :=
  {| moreno16_concrete_lambda := moreno16_arbitrary_lambda W;
     moreno16_concrete_lambda_pos := moreno16_arbitrary_lambda_pos W;
     moreno16_concrete_vlambda_dim := moreno16_arbitrary_vlambda_dim W;
     moreno16_concrete_vlambda_is_h_module_dim :=
       moreno16_arbitrary_vlambda_is_h_module_dim W |}.

Definition moreno16_arbitrary_witness_to_hypotheses
  (W : Moreno16ArbitraryAVlambdaWitness)
  : Moreno16ArbitraryAConcreteHypotheses :=
  moreno16_build_arbitrary_a_concrete_hypotheses
    (moreno16_arbitrary_a W)
    (moreno16_arbitrary_a_unit W)
    (moreno16_arbitrary_a_pure W)
    (moreno16_arbitrary_witness_to_concrete W).

Definition moreno16_build_arbitrary_a_witness_from_concrete_hypotheses
  (H : Moreno16ArbitraryAConcreteVlambdaHypotheses)
  : Moreno16ArbitraryAVlambdaWitness :=
  {| moreno16_arbitrary_a := moreno16_concrete_hyp_a H;
     moreno16_arbitrary_a_unit := moreno16_concrete_hyp_a_unit H;
     moreno16_arbitrary_a_pure := moreno16_concrete_hyp_a_pure H;
     moreno16_arbitrary_lambda := moreno16_concrete_hyp_lambda H;
     moreno16_arbitrary_lambda_pos := moreno16_concrete_hyp_lambda_pos H;
     moreno16_arbitrary_vlambda_dim := moreno16_concrete_hyp_vlambda_dim H;
     moreno16_arbitrary_vlambda_is_h_module_dim :=
       moreno16_concrete_hyp_vlambda_is_h_module_dim H |}.

Definition moreno16_geometry_to_concrete_hypotheses
  (G : Moreno16ArbitraryAGeometricVlambdaData)
  : Moreno16ArbitraryAConcreteVlambdaHypotheses :=
  {| moreno16_concrete_hyp_a := moreno16_geom_a G;
     moreno16_concrete_hyp_a_unit := moreno16_geom_a_unit G;
     moreno16_concrete_hyp_a_pure := moreno16_geom_a_pure G;
     moreno16_concrete_hyp_lambda := moreno16_geom_lambda G;
     moreno16_concrete_hyp_lambda_pos := moreno16_geom_lambda_pos G;
     moreno16_concrete_hyp_vlambda_dim := moreno16_geom_vlambda_dim G;
     moreno16_concrete_hyp_vlambda_is_h_module_dim :=
       moreno16_geometry_is_h_module_dim G |}.

Definition moreno16_concrete_hypotheses_to_hypotheses
  (H : Moreno16ArbitraryAConcreteVlambdaHypotheses)
  : Moreno16ArbitraryAConcreteHypotheses :=
  moreno16_arbitrary_witness_to_hypotheses
    (moreno16_build_arbitrary_a_witness_from_concrete_hypotheses H).

Definition moreno16_geometry_to_witness
  (G : Moreno16ArbitraryAGeometricVlambdaData)
  : Moreno16ArbitraryAVlambdaWitness :=
  moreno16_build_arbitrary_a_witness_from_concrete_hypotheses
    (moreno16_geometry_to_concrete_hypotheses G).

Theorem moreno16_arbitrary_witness_dim_div4 :
  forall W : Moreno16ArbitraryAVlambdaWitness,
    exists k : nat, moreno16_arbitrary_vlambda_dim W = 4 * k.
Proof.
  intro W.
  exact (moreno16_concrete_witness_dim_div4
           (moreno16_arbitrary_witness_to_concrete W)).
Qed.

Corollary moreno16_arbitrary_witness_dim_mod4 :
  forall W : Moreno16ArbitraryAVlambdaWitness,
    Nat.modulo (moreno16_arbitrary_vlambda_dim W) 4 = 0.
Proof.
  intro W.
  exact (moreno16_concrete_witness_dim_mod4
           (moreno16_arbitrary_witness_to_concrete W)).
Qed.

Theorem moreno16_concrete_hypotheses_dim_div4 :
  forall H : Moreno16ArbitraryAConcreteVlambdaHypotheses,
    exists k : nat, moreno16_concrete_hyp_vlambda_dim H = 4 * k.
Proof.
  intro H.
  exact
    (moreno16_arbitrary_witness_dim_div4
       (moreno16_build_arbitrary_a_witness_from_concrete_hypotheses H)).
Qed.

Corollary moreno16_concrete_hypotheses_dim_mod4 :
  forall H : Moreno16ArbitraryAConcreteVlambdaHypotheses,
    Nat.modulo (moreno16_concrete_hyp_vlambda_dim H) 4 = 0.
Proof.
  intro H.
  exact
    (moreno16_arbitrary_witness_dim_mod4
       (moreno16_build_arbitrary_a_witness_from_concrete_hypotheses H)).
Qed.

Theorem moreno16_geometry_dim_div4 :
  forall G : Moreno16ArbitraryAGeometricVlambdaData,
    exists k : nat, moreno16_geom_vlambda_dim G = 4 * k.
Proof.
  intro G.
  exists (moreno16_geom_block_count G).
  exact (moreno16_geom_vlambda_dim_is_blocks G).
Qed.

Corollary moreno16_geometry_dim_mod4 :
  forall G : Moreno16ArbitraryAGeometricVlambdaData,
    Nat.modulo (moreno16_geom_vlambda_dim G) 4 = 0.
Proof.
  intro G.
  rewrite (moreno16_geom_vlambda_dim_is_blocks G).
  rewrite Nat.mul_comm.
  apply Nat.Div0.mod_mul.
Qed.
