(** * WalkerFermatAlgebras: Walker (1954) Fermat's Theorem for Algebras -- reference stub.

    Source: Walker, G.L. (1954) "Fermat's Theorem for Algebras",
    Pacific J. Math., Vol. 4, No. 2, pp. 317-320.
    PDF: tier1_core_cd_algebra/broader_cd_theory/walker_1954_...

    * Role in the CD tower formalization:

    Walker's paper generalizes Fermat's little theorem (x^{p^n} = x over GF(p^n))
    to matrix algebras and semi-simple algebras over finite fields.  The setting
    is GF(p^n) -- Galois fields of prime-power order -- NOT the real or complex
    field that underlies our Cayley-Dickson tower.

    WHY we record this here despite the domain mismatch:

    (a) Polynomial identities over algebras.  Walker's ideal J(A) = { f(x) in
        F[x] : f(a) = 0 for all a in A } is the single-variable analogue of
        the polynomial-identity theory that Kaplansky (1948) and Levitzki (1950)
        developed for multilinear identities.  The CD tower satisfies its own
        polynomial identities (alternativity at dim 8, power-associativity at
        all levels), and comparing these to Walker's finite-field identities
        clarifies what is special about characteristic 0.

    (b) Structure theory bridge.  Walker's Theorem 4 for semi-simple algebras
        relies on the Artin-Wedderburn decomposition (every semi-simple algebra
        decomposes as a direct sum of matrix algebras over division rings).
        The same structure theorem appears in our project via
        WedderburnPrimitive.v and HModuleDim.v.

    (c) Schafer's division-algebra criterion.  Schafer (1945) showed that the
        CD process over certain non-real fields CAN yield a division algebra
        at dimension 16 (see SchaferDivAlg16.v, POSITIVE result).  Walker's
        f(m, p^n, x) polynomial gives the precise annihilating polynomial for
        total matrix algebras over those same finite fields.  When the CD
        algebra over a finite field is NOT a division algebra, it decomposes
        via Artin-Wedderburn, and Walker's theorem determines J(A).

    (d) Finite-field CD algebras.  One can perform the Cayley-Dickson
        construction over GF(p^n) instead of R.  The resulting algebras are
        finite and their polynomial identities are governed by Walker's
        theorems whenever they decompose as sums of matrix algebras.
        CDScalarExtension.v proves the CD linearity axioms hold over any
        commutative ring, which includes GF(p^n).

    * Mathematical content (pp. 317-320):

    SECTION 2 -- An ideal of polynomial identities:

    DEFINITION: For an algebra A over F and indeterminate x, define
      J(A) := { f(x) in F[x] : f(a) = 0 for all a in A }.

    LEMMA 1 (p.317): J(A) is a principal ideal in F[x].
      Proof is immediate from F[x] being a PID.

    THEOREM 1 (p.317): For A = M_m(GF(p^n)) (total matrix algebra of order
      m^2 over GF(p^n)), J(A) is the principal ideal generated by f(m, p^n, x),
      the monic LCM of ALL monic polynomials of degree m in GF(p^n)[x].
      Key fact used: every monic polynomial of degree m over GF(p^n) is the
      minimal polynomial of some element of M_m(GF(p^n)) [Perlis 1952, p.148].

    LEMMA 2 (p.318): If A is a subalgebra of B then J(A) contains J(B).
      (Larger algebra => fewer universal polynomial identities.)

    LEMMA 3 (p.318): J(A_1 + A_2) = J(A_1) intersect J(A_2).
      Direct-sum decomposition: a = a_1 + a_2 with a_1*a_2 = 0 implies
      f(a) = f(a_1) + f(a_2), so f annihilates the sum iff it annihilates
      each component.

    THEOREM 2 (p.318): If A = A_1 + ... + A_k, each A_i = M_{m_i}(GF(p^n))
      with m_1 <= m_2 <= ... <= m_k, then J(A) = (f(m_k, p^n, x)).
      The largest matrix block determines the identity ideal.

    SECTION 3 -- A determination of f(m, p^n, x):

    THEOREM 3 (p.318): f(m, p^n, x) = (x^{p^n} - x)(x^{p^{2n}} - x) ... (x^{p^{mn}} - x).
      When m = 1 this reduces to x^{p^n} - x, i.e., classical Fermat.

    LEMMA 4 (p.318): f(m, p^n, x) = (x^{p^{mn}} - x) * f(m-1, p^n, x).
      Proved by counting multiplicities of irreducible factors g_k(x) of
      degree k dividing m: the multiplicity of g_k in f(m,...) equals its
      multiplicity in f(m-1,...) plus 1 when k | m, plus 0 otherwise.
      Uses: x^{p^{mn}} - x = product of all irreducible g_k with k | mn
      [Dickson 1901, p.17].

    SECTION 4 -- Further results concerning J(A):

    THEOREM 4 (p.319): For A semi-simple of characteristic p, with simple
      components of orders m_1^2, ..., m_k^2 over centers GF(p^{n_1}), ...,
      GF(p^{n_k}), J(A) is generated by
        lcm( f(m_1, p^{n_1}, x), ..., f(m_k, p^{n_k}, x) ).

    THEOREM 5 (p.319): For A with radical N of nilpotency index r,
      if J(A/N) = (f) and J(N) = (x^r), then
        (g_1) contains J(A) contains (g_2)
      where g_1 = lcm(x^r, f(x))  and  g_2 = [f(x)]^r.
      The bounds are sharp: Walker gives a GF(2) counterexample showing
      (g_1) != (g_2) in general (p.320, remark).

    REMARK (p.320): Sharpness example over F = GF(2).
      A_1 = span{e_{11}, e_{12}}: J(A_1) = (x^3 - x^2).
      A_2 = span{e_{11}, e_{12}, e_{22}}: J(A_2) = (x^4 - x^2) = ((x^2-x)^2).
      Both have radical index 2 and f(x) = x^2 - x, but (g_1) != (g_2).

    * References cited by Walker:

    [1] L.E. Dickson, Linear Groups (1901) -- Galois field theory.
    [2] I. Kaplansky, Rings with a polynomial identity (1948).
    [3] J. Levitzki, A theorem on polynomial identities (1950).
    [4] I. Niven, Fermat's theorem for matrices (1948).
    [5] S. Perlis, Theory of matrices (1952).

    * What we do NOT formalize:

    This file is a REFERENCE STUB.  Walker's results live entirely in the
    finite-field / matrix-algebra setting.  No computable content is extracted
    because:

    1. Our CD tower operates over R (characteristic 0), where x^{p^n} - x
       has no meaning as a universal identity.

    2. The polynomial identities relevant to our CD algebras are
       ALTERNATIVITY (dim 8, formalized in SedenionAlternativityFails.v)
       and POWER-ASSOCIATIVITY (all levels, used implicitly in norm proofs).

    3. The Artin-Wedderburn decomposition that Walker relies on is already
       captured by WedderburnPrimitive.v and HModuleDim.v for our purposes.

    If the project later explores CD algebras over finite fields (e.g.,
    verifying Schafer's positive result computationally), Walker's explicit
    formula for f(m, p^n, x) becomes directly relevant.

    Mirrors: WedderburnPrimitive.v, SchaferDivAlg16.v, CDScalarExtension.v
    See also: GF2Algebra.v (GF(2) polynomial evaluation, closest finite-field theory) *)

From Stdlib Require Import Reals.

(** Walker's central object: the ideal J(A) of polynomial identities.

    For an algebra A over a field F, J(A) is the set of all univariate
    polynomials f(x) in F[x] satisfying f(a) = 0 for every a in A.

    Lemma 1: J(A) is a principal ideal (F[x] is a PID).
    Theorem 1: For M_m(GF(p^n)), J(A) = (f(m, p^n, x)).

    Over R (our setting), J(M_m(R)) = {0} because R[x] has irreducible
    polynomials of every degree, so no nonzero polynomial can annihilate
    all m x m real matrices.  Walker's results are nontrivial precisely
    because GF(p^n) has only finitely many irreducible polynomials of
    each degree. *)

(** Walker's explicit formula (Theorem 3):

    f(m, p^n, x) = prod_{j=1}^{m} (x^{p^{jn}} - x)

    Degree of f(m, p^n, x) = p^n + p^{2n} + ... + p^{mn}.

    Special cases:
    - m = 1: f(1, p^n, x) = x^{p^n} - x (classical Fermat / Freshman's dream).
    - m = 1, n = 1: f(1, p, x) = x^p - x (Fermat's little theorem).
    - m = 2, n = 1, p = 2: f(2, 2, x) = (x^2 - x)(x^4 - x), degree 6.

    The recursive structure (Lemma 4):
      f(m, p^n, x) = (x^{p^{mn}} - x) * f(m-1, p^n, x)
    mirrors the tower-like growth of the CD construction, where each
    doubling introduces new structure on top of the previous level. *)

(** Connection to the CD tower over finite fields:

    The CD construction can be performed over GF(p^n) via CDScalarExtension.v.
    At dimension 2^k, the resulting algebra is either:

    (a) A division algebra (when the norm form is anisotropic over GF(p^n)),
        in which case J(A) = (x^{|A|} - x) by a generalization of Wedderburn's
        little theorem (every finite division ring is a field).

    (b) NOT a division algebra (the generic case for dim >= 16 over most
        fields, and always for dim >= 16 over R by Schafer 1945), in which
        case the Artin-Wedderburn decomposition applies and Walker's
        Theorem 4 determines J(A) as the LCM of the component ideals.

    For the standard CD tower over GF(2):
    - dim 1 (GF(2) itself): J = (x^2 - x).
    - dim 2 (GF(4)): J = (x^4 - x) since GF(4) is a field.
    - dim 4 (quaternions over GF(2)): J depends on whether this is M_2(GF(2))
      or a division ring.  Over GF(2), the quaternion algebra is M_2(GF(2)),
      so J = (f(2, 2, x)) = ((x^2 - x)(x^4 - x)).
    - dim 8+: structure depends on the CD parameters chosen. *)
