(** * WedderburnPrimitive: Wedderburn (1914) Primitive Algebras -- reference stub.

    Source: Wedderburn, J.H.M. (1914) "A Type of Primitive Algebra",
    Trans. Amer. Math. Soc., 15(2), pp. 162-166.
    PDF: tier1_core_cd_algebra/foundational_legacy/wedderburn_1914_...
    DOI: 10.1090/S0002-9947-1914-1500970-5

    * Role in the CD tower formalization:

    Wedderburn's paper establishes the structural theory of "primitive"
    (= division) algebras defined by cyclic relations xy = y*theta(x), y^n = g.
    This is the theoretical foundation for:

    (a) The Artin-Wedderburn theorem: every simple algebra is isomorphic to
        a matrix ring over a division ring.  We use this in HModuleDim.v
        (via the is_h_module_dim inductive predicate) to prove that
        quaternion modules have dimension divisible by 4.

    (b) Schafer (1945) uses Wedderburn's structure theory to analyze
        when the CD process yields a division algebra.

    (c) The n=2 case (Wedderburn p.162) IS the quaternion algebra:
        xy = y*theta(x) with theta(x) = conjugate, y^2 = -1.

    * Mathematical content (pp. 162-166):

    THEOREM (p.163): A normal primitive algebra whose group of the
    identical equation is cyclic is generated by x, y satisfying
      xy = y * theta(x),    y^n = g
    where theta and g are rational in the coefficient field, and
    y^n is the first power of y commutative with x.

    Section 1 (pp. 162-164): Structure of normal primitive algebras
    - Primitive idempotents e_r from roots xi_r of f(x) = 0
    - Matric form via conjugation: e_{r,r+1} chosen so products cycle
    - Every element z = y^r * h_0 + ... + y * h_{n-2} + h_{n-1}
    - Coefficients h_r are rational polynomials in x

    Section 2 (pp. 164-166): Conditions for Dickson's algebra to be primitive
    - Determinant condition: det(z) != 0 for all nonzero z
    - Two types: y + phi(x) form (always invertible if g not a norm),
      and elements independent of y (invertible iff determinant nonzero)
    - CRITERION: g must not be the norm of any rational function of xi

    * What we formalize:

    This file is a REFERENCE STUB.  The paper's main contribution to
    our project is STRUCTURAL CONTEXT, not directly computable content.
    The concrete consequences are:

    1. Quaternions are a primitive (division) algebra -- already proved
       in DicksonCDProcess.v (dickson_quat_right_inverse).

    2. Quaternion modules have dim = 4k -- proved in HModuleDim.v
       via the is_h_module_dim predicate (which encodes Wedderburn's
       division-ring module theory at the nat level).

    3. The determinant invertibility condition -- this is what Schafer
       uses to show sedenions fail.  Formalized in SchaferDivAlg16.v
       (schafer_eq2_singular_witness).

    Mirrors: HModuleDim.v, FinDimHModule.v, DicksonCDProcess.v
    Supports claims: C-1543 (annihilator mod-4 bound). *)

From Stdlib Require Import Reals.

(** Wedderburn's key structural fact used in our proofs:

    Every finitely generated module over a division ring (= primitive
    algebra in Wedderburn's terminology) is free, and therefore has
    dimension divisible by the dimension of the division ring.

    For H (quaternions, dim 4): every H-module has dim = 4k.

    This is the conceptual foundation for:
    - FinDimHModule.is_h_module_dim
    - HModuleDim.h_module_dim_div4
    - C1543_MorMod4Bound.cor_1_17_mod4 *)

(** The quaternion case of Wedderburn's theorem:
    H is a primitive algebra with n = 2, theta = conjugate, g = -1.
    The relation xy = y*conj(x), y^2 = -1 generates H from {x, y}
    where x = i and y = j give k = ij.

    This is exactly the quaternion multiplication table from
    Dickson (1919) eq.3, formalized in DicksonCDProcess.v. *)
