(** * WedderburnPrimitive: Wedderburn (1914) Primitive Algebras.

    Source: Wedderburn, J.H.M. (1914) "A Type of Primitive Algebra",
    Trans. Amer. Math. Soc., 15(2), pp. 162-166.
    PDF: tier1_core_cd_algebra/foundational_legacy/wedderburn_1914_...
    DOI: 10.1090/S0002-9947-1914-1500970-5

    * Role in the CD tower formalization:

    Wedderburn's paper establishes the structural theory of "primitive"
    (= division) algebras defined by cyclic relations xy = y*theta(x), y^n = g.
    This is the theoretical foundation for:

    (a) The Artin-Wedderburn theorem: every simple algebra is isomorphic to
        a matrix ring over a division ring.  We use this in HModuleDim.v
        (via the is_h_module_dim inductive predicate) to prove that
        quaternion modules have dimension divisible by 4.

    (b) Schafer (1945) uses Wedderburn's structure theory to analyze
        when the CD process yields a division algebra.

    (c) The n=2 case (Wedderburn p.162) IS the quaternion algebra:
        xy = y*theta(x) with theta(x) = conjugate, y^2 = -1.

    * Mathematical content (pp. 162-166):

    THEOREM (p.163): A normal primitive algebra whose group of the
    identical equation is cyclic is generated by x, y satisfying
      xy = y * theta(x),    y^n = g
    where theta and g are rational in the coefficient field, and
    y^n is the first power of y commutative with x.

    Section 1 (pp. 162-164): Structure of normal primitive algebras
    - Primitive idempotents e_r from roots xi_r of f(x) = 0
    - Matric form via conjugation: e_{r,r+1} chosen so products cycle
    - Every element z = y^r * h_0 + ... + y * h_{n-2} + h_{n-1}
    - Coefficients h_r are rational polynomials in x

    Section 2 (pp. 164-166): Conditions for Dickson's algebra to be primitive
    - Determinant condition: det(z) != 0 for all nonzero z
    - Two types: y + phi(x) form (always invertible if g not a norm),
      and elements independent of y (invertible iff determinant nonzero)
    - CRITERION: g must not be the norm of any rational function of xi

    * What we formalize:

    This file now carries a compact paper-scoped theorem surface for the
    consequences the rest of the repo actually reuses.  It is still not a
    line-by-line full formalization of Wedderburn's paper, but it is no
    longer only prose context.  The concrete consequences are:

    1. Quaternions are a primitive (division) algebra -- already proved
       in DicksonCDProcess.v (dickson_quat_right_inverse).

    2. Quaternion modules have dim = 4k -- proved in HModuleDim.v
       via the is_h_module_dim predicate (which encodes Wedderburn's
       division-ring module theory at the nat level).

    3. The determinant invertibility condition -- this is what Schafer
       uses to show sedenions fail.  Formalized in SchaferDivAlg16.v
       (schafer_eq2_singular_witness).

    Mirrors: HModuleDim.v, FinDimHModule.v, DicksonCDProcess.v
    Supports claims: C-1543 (annihilator mod-4 bound). *)

From Stdlib Require Import Reals Arith Lra Psatz.
From OpenGororoba Require Import
  FinDimHModule CayleyDicksonAlgebra DicksonCDProcess Dickson1921.

Open Scope R_scope.

(** Wedderburn's key structural fact used in our proofs:

    Every finitely generated module over a division ring (= primitive
    algebra in Wedderburn's terminology) is free, and therefore has
    dimension divisible by the dimension of the division ring.

    For H (quaternions, dim 4): every H-module has dim = 4k.

    This is the conceptual foundation for:
    - FinDimHModule.is_h_module_dim
    - HModuleDim.h_module_dim_div4
    - C1543_MorMod4Bound.cor_1_17_mod4 *)

(** The quaternion case of Wedderburn's theorem:
    H is a primitive algebra with n = 2, theta = conjugate, g = -1.
    The relation xy = y*conj(x), y^2 = -1 generates H from {x, y}
    where x = i and y = j give k = ij.

    This is exactly the quaternion multiplication table from
    Dickson (1919) eq.3, formalized in DicksonCDProcess.v. *)

(** Wedderburn surface used downstream: valid quaternion-module dimensions
    are multiples of 4. This is the nat-level form of the standard
    division-ring module theorem specialized to H. *)
Theorem wedderburn_h_module_dim_div4 : forall d : nat,
  is_h_module_dim d -> exists k : nat, d = (4 * k)%nat.
Proof.
  exact FinDimHModule.h_module_dim_div4.
Qed.

(** Exact characterization of the valid H-module dimensions. *)
Theorem wedderburn_h_module_dim_iff_div4 : forall d : nat,
  is_h_module_dim d <-> exists k : nat, d = (4 * k)%nat.
Proof.
  exact FinDimHModule.h_module_dim_iff_div4.
Qed.

(** Mod-4 corollary used by the Moreno lane. *)
Theorem wedderburn_h_module_dim_mod4 : forall d : nat,
  is_h_module_dim d -> Nat.modulo d 4%nat = 0%nat.
Proof.
  exact FinDimHModule.h_module_dim_mod4.
Qed.

Record WedderburnCyclicN2Surface (A : Type) := {
  wcy_mul : A -> A -> A;
  wcy_theta : A -> A;
  wcy_x : A;
  wcy_y : A;
  wcy_g : A;
  wcy_cyclic_relation :
    wcy_mul wcy_x wcy_y = wcy_mul wcy_y (wcy_theta wcy_x);
  wcy_y_square : wcy_mul wcy_y wcy_y = wcy_g;
}.

Record WedderburnPrimitiveN2Surface (A : Type) := {
  wp_cyclic_surface : WedderburnCyclicN2Surface A;
  wp_one : A;
  wp_det : A -> R;
  wp_norm : A -> R;
  wp_inv : A -> A;
  wp_det_norm_sq : forall z : A, wp_det z = (wp_norm z)^2;
  wp_det_nonzero_iff_norm_nonzero :
    forall z : A, wp_det z <> 0 <-> wp_norm z <> 0;
  wp_right_inverse :
    forall z : A, wp_det z <> 0 ->
      @wcy_mul A wp_cyclic_surface z (wp_inv z) = wp_one;
  wp_left_inverse :
    forall z : A, wp_det z <> 0 ->
      @wcy_mul A wp_cyclic_surface (wp_inv z) z = wp_one;
}.

(** Wedderburn's cyclic presentation in the quaternion case:
    choose x = i and y = j. Then xy = y * theta(x) with theta = conjugation,
    and y^2 = -1. *)
Theorem wedderburn_quaternion_cyclic_relation :
  quat_mul qi qj = quat_mul qj (quat_conj qi).
Proof.
  unfold qi, qj, quat_conj, quat_mul.
  simpl.
  f_equal; ring.
Qed.

Theorem wedderburn_quaternion_y_square :
  quat_mul qj qj = quat_neg quat_one.
Proof.
  unfold qj, quat_neg, quat_one, quat_mul.
  simpl.
  f_equal; ring.
Qed.

Definition wedderburn_quaternion_cyclic_surface :
    WedderburnCyclicN2Surface CDQuat :=
  {| wcy_mul := quat_mul;
     wcy_theta := quat_conj;
     wcy_x := qi;
     wcy_y := qj;
     wcy_g := quat_neg quat_one;
     wcy_cyclic_relation := wedderburn_quaternion_cyclic_relation;
     wcy_y_square := wedderburn_quaternion_y_square |}.

(** The full quaternion basis is generated from the cyclic pair {i, j}. *)
Theorem wedderburn_quaternion_cyclic_generation :
  qk = quat_mul qi qj /\
  qi = quat_mul qj qk /\
  qj = quat_mul qk qi.
Proof.
  repeat split.
  - symmetry. exact dickson_eq3_ij.
  - symmetry. exact dickson_eq3_jk.
  - symmetry. exact dickson_eq3_ki.
Qed.

Definition wedderburn_quaternion_left_det (q : CDQuat) : R :=
  dickson1921_matrix_det4 (quat_hamilton_entry q).

(** Wedderburn's determinant criterion, specialized to the quaternion case:
    the left-multiplication determinant is exactly the norm square squared. *)
Theorem wedderburn_quaternion_det_equals_norm_sq :
  forall q : CDQuat,
    wedderburn_quaternion_left_det q = (quat_norm_sq q)^2.
Proof.
  intro q.
  unfold wedderburn_quaternion_left_det.
  unfold dickson1921_matrix_det4.
  repeat rewrite <- dickson1921_param_matrix_specializes_to_standard.
  exact (proj1 (dickson1921_param_quaternion_case q)).
Qed.

Theorem wedderburn_quaternion_det_nonzero_iff_norm_nonzero :
  forall q : CDQuat,
    wedderburn_quaternion_left_det q <> 0 <-> quat_norm_sq q <> 0.
Proof.
  intro q.
  rewrite wedderburn_quaternion_det_equals_norm_sq.
  split.
  - intros Hdet Hn.
    apply Hdet.
    nra.
  - intros Hn Hdet.
    apply Hn.
    nra.
Qed.

(** In the quaternion case, Wedderburn's determinant condition is enough to
    recover a right inverse through Dickson's explicit norm formula. *)
Theorem wedderburn_quaternion_det_implies_right_inverse :
  forall q : CDQuat,
    wedderburn_quaternion_left_det q <> 0 ->
    exists r : CDQuat, quat_mul q r = quat_one.
Proof.
  intros q Hdet.
  exists (quat_inv q).
  apply dickson_quat_right_inverse.
  intro Hn.
  apply Hdet.
  rewrite wedderburn_quaternion_det_equals_norm_sq.
  nra.
Qed.

Theorem wedderburn_quaternion_det_implies_left_inverse :
  forall q : CDQuat,
    wedderburn_quaternion_left_det q <> 0 ->
    exists l : CDQuat, quat_mul l q = quat_one.
Proof.
  intros [a b c d] Hdet.
  exists (quat_inv {| qa := a; qb := b; qc := c; qd := d |}).
  unfold quat_inv, quat_mul, quat_conj, quat_scale, quat_one, quat_norm_sq.
  simpl in *.
  assert (Hn' : a * a + b * b + c * c + d * d <> 0).
  {
    intro Habs.
    apply Hdet.
    rewrite wedderburn_quaternion_det_equals_norm_sq.
    unfold quat_norm_sq in *.
    simpl in *.
    nra.
  }
  repeat f_equal; field; exact Hn'.
Qed.

Theorem wedderburn_quaternion_two_sided_inverse :
  forall q : CDQuat,
    wedderburn_quaternion_left_det q <> 0 ->
    quat_mul q (quat_inv q) = quat_one /\
    quat_mul (quat_inv q) q = quat_one.
Proof.
  intros q Hdet.
  split.
  - apply dickson_quat_right_inverse.
    intro Hn.
    apply Hdet.
    rewrite wedderburn_quaternion_det_equals_norm_sq.
    nra.
  - destruct q as [a b c d].
    unfold quat_inv, quat_mul, quat_conj, quat_scale, quat_one, quat_norm_sq.
    simpl in *.
    assert (Hn' : a * a + b * b + c * c + d * d <> 0).
    {
      intro Habs.
      apply Hdet.
      rewrite wedderburn_quaternion_det_equals_norm_sq.
      unfold quat_norm_sq in *.
      simpl in *.
      nra.
    }
    repeat f_equal; field; exact Hn'.
Qed.

Definition wedderburn_quaternion_primitive_surface :
    WedderburnPrimitiveN2Surface CDQuat :=
  {| wp_cyclic_surface := wedderburn_quaternion_cyclic_surface;
     wp_one := quat_one;
     wp_det := wedderburn_quaternion_left_det;
     wp_norm := quat_norm_sq;
     wp_inv := quat_inv;
     wp_det_norm_sq := wedderburn_quaternion_det_equals_norm_sq;
     wp_det_nonzero_iff_norm_nonzero :=
       wedderburn_quaternion_det_nonzero_iff_norm_nonzero;
     wp_right_inverse := fun z Hz => proj1 (wedderburn_quaternion_two_sided_inverse z Hz);
     wp_left_inverse := fun z Hz => proj2 (wedderburn_quaternion_two_sided_inverse z Hz) |}.

(** Packaged surface for the two main Wedderburn consequences used later:
    cyclic generation in the n=2 quaternion case, and the determinant
    criterion for invertibility. *)
Theorem wedderburn_quaternion_surface_summary :
  quat_mul qi qj = quat_mul qj (quat_conj qi) /\
  quat_mul qj qj = quat_neg quat_one /\
  (qk = quat_mul qi qj /\
   qi = quat_mul qj qk /\
   qj = quat_mul qk qi) /\
  (forall q : CDQuat,
      wedderburn_quaternion_left_det q = (quat_norm_sq q)^2) /\
  (forall q : CDQuat,
      wedderburn_quaternion_left_det q <> 0 <-> quat_norm_sq q <> 0) /\
  (forall q : CDQuat,
      wedderburn_quaternion_left_det q <> 0 ->
      exists r : CDQuat, quat_mul q r = quat_one) /\
  (forall q : CDQuat,
      wedderburn_quaternion_left_det q <> 0 ->
      exists l : CDQuat, quat_mul l q = quat_one).
Proof.
  split.
  - exact wedderburn_quaternion_cyclic_relation.
  - split.
    + exact wedderburn_quaternion_y_square.
    + split.
      * exact wedderburn_quaternion_cyclic_generation.
      * split.
        -- exact wedderburn_quaternion_det_equals_norm_sq.
        -- split.
           ++ exact wedderburn_quaternion_det_nonzero_iff_norm_nonzero.
           ++ split.
              ** exact wedderburn_quaternion_det_implies_right_inverse.
              ** exact wedderburn_quaternion_det_implies_left_inverse.
Qed.

Definition wedderburn_generalized_quaternion_left_det
    (c2 c3 : R) (q : CDQuat) : R :=
  dickson1921_matrix_det4 (dickson1921_param_matrix_entry c2 c3 q).

Definition wedderburn_generalized_quaternion_inv
    (c2 c3 : R) (q : CDQuat) : CDQuat :=
  quat_scale (/ (dickson1921_param_norm c2 c3 q)) (quat_conj q).

(** Wedderburn's cyclic presentation extends from the ordinary quaternion
    case to the generalized quaternion family in Dickson's notation. *)
Theorem wedderburn_generalized_quaternion_cyclic_relation :
  forall c2 c3 : R,
    dickson1921_param_mul c2 c3 qi qj =
    dickson1921_param_mul c2 c3 qj (quat_conj qi).
Proof.
  intros c2 c3.
  unfold dickson1921_param_mul, qi, qj, quat_conj.
  simpl.
  f_equal; ring.
Qed.

Theorem wedderburn_generalized_quaternion_y_square :
  forall c2 c3 : R,
    dickson1921_param_mul c2 c3 qj qj = quat_scale c3 quat_one.
Proof.
  exact dickson1921_param_j_sq.
Qed.

Definition wedderburn_generalized_quaternion_cyclic_surface
    (c2 c3 : R) : WedderburnCyclicN2Surface CDQuat :=
  {| wcy_mul := dickson1921_param_mul c2 c3;
     wcy_theta := quat_conj;
     wcy_x := qi;
     wcy_y := qj;
     wcy_g := quat_scale c3 quat_one;
     wcy_cyclic_relation :=
       wedderburn_generalized_quaternion_cyclic_relation c2 c3;
     wcy_y_square := wedderburn_generalized_quaternion_y_square c2 c3 |}.

Theorem wedderburn_generalized_quaternion_cyclic_generation :
  forall c2 c3 : R,
    c2 <> 0 ->
    c3 <> 0 ->
    qk = dickson1921_param_mul c2 c3 qi qj /\
    qi = quat_scale (- / c3) (dickson1921_param_mul c2 c3 qj qk) /\
    qj = quat_scale (- / c2) (dickson1921_param_mul c2 c3 qk qi).
Proof.
  intros c2 c3 Hc2 Hc3.
  split.
  - symmetry. exact (dickson1921_param_ij c2 c3).
  - split.
    + rewrite dickson1921_param_jk.
      unfold quat_scale, qi.
      simpl.
      repeat f_equal; field; exact Hc3.
    + rewrite dickson1921_param_ki.
      unfold quat_scale, qj.
      simpl.
      repeat f_equal; field; exact Hc2.
Qed.

Theorem wedderburn_generalized_quaternion_det_equals_norm_sq :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_generalized_quaternion_left_det c2 c3 q =
    (dickson1921_param_norm c2 c3 q)^2.
Proof.
  exact dickson1921_param_det_equals_norm_sq.
Qed.

Theorem wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 <->
    dickson1921_param_norm c2 c3 q <> 0.
Proof.
  intros c2 c3 q.
  rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
  split.
  - intros Hdet Hn.
    apply Hdet.
    nra.
  - intros Hn Hdet.
    apply Hn.
    nra.
Qed.

Theorem wedderburn_generalized_quaternion_right_inverse :
  forall c2 c3 : R, forall q : CDQuat,
    dickson1921_param_norm c2 c3 q <> 0 ->
    dickson1921_param_mul c2 c3 q
      (wedderburn_generalized_quaternion_inv c2 c3 q) = quat_one.
Proof.
  intros c2 c3 [a b c d] Hn.
  unfold dickson1921_param_norm in Hn.
  simpl in Hn.
  assert (Hn' : a * a - c2 * (b * b) - c3 * (c * c) + c2 * c3 * (d * d) <> 0).
  {
    intro Habs.
    apply Hn.
    lra.
  }
  unfold wedderburn_generalized_quaternion_inv, dickson1921_param_mul,
         dickson1921_param_norm, quat_scale, quat_conj, quat_one.
  simpl in *.
  repeat f_equal; field;
  exact Hn'.
Qed.

Theorem wedderburn_generalized_quaternion_det_implies_right_inverse :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 ->
    exists r : CDQuat, dickson1921_param_mul c2 c3 q r = quat_one.
Proof.
  intros c2 c3 q Hdet.
  exists (wedderburn_generalized_quaternion_inv c2 c3 q).
  apply wedderburn_generalized_quaternion_right_inverse.
  intro Hn.
  apply Hdet.
  rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
  nra.
Qed.

Theorem wedderburn_generalized_quaternion_left_inverse :
  forall c2 c3 : R, forall q : CDQuat,
    dickson1921_param_norm c2 c3 q <> 0 ->
    dickson1921_param_mul c2 c3
      (wedderburn_generalized_quaternion_inv c2 c3 q) q = quat_one.
Proof.
  intros c2 c3 [a b c d] Hn.
  unfold dickson1921_param_norm in Hn.
  simpl in Hn.
  assert (Hn' : a * a - c2 * (b * b) - c3 * (c * c) + c2 * c3 * (d * d) <> 0).
  {
    intro Habs.
    apply Hn.
    lra.
  }
  unfold wedderburn_generalized_quaternion_inv, dickson1921_param_mul,
         dickson1921_param_norm, quat_scale, quat_conj, quat_one.
  simpl in *.
  repeat f_equal; field; exact Hn'.
Qed.

Theorem wedderburn_generalized_quaternion_det_implies_left_inverse :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 ->
    exists l : CDQuat, dickson1921_param_mul c2 c3 l q = quat_one.
Proof.
  intros c2 c3 q Hdet.
  exists (wedderburn_generalized_quaternion_inv c2 c3 q).
  apply wedderburn_generalized_quaternion_left_inverse.
  intro Hn.
  apply Hdet.
  rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
  nra.
Qed.

Theorem wedderburn_generalized_quaternion_two_sided_inverse :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 ->
    dickson1921_param_mul c2 c3 q
      (wedderburn_generalized_quaternion_inv c2 c3 q) = quat_one /\
    dickson1921_param_mul c2 c3
      (wedderburn_generalized_quaternion_inv c2 c3 q) q = quat_one.
Proof.
  intros c2 c3 q Hdet.
  split.
  - apply wedderburn_generalized_quaternion_right_inverse.
    intro Hn.
    apply Hdet.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
    nra.
  - apply wedderburn_generalized_quaternion_left_inverse.
    intro Hn.
    apply Hdet.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
    nra.
Qed.

Definition wedderburn_generalized_quaternion_primitive_surface
    (c2 c3 : R) : WedderburnPrimitiveN2Surface CDQuat :=
  {| wp_cyclic_surface := wedderburn_generalized_quaternion_cyclic_surface c2 c3;
     wp_one := quat_one;
     wp_det := wedderburn_generalized_quaternion_left_det c2 c3;
     wp_norm := dickson1921_param_norm c2 c3;
     wp_inv := wedderburn_generalized_quaternion_inv c2 c3;
     wp_det_norm_sq := wedderburn_generalized_quaternion_det_equals_norm_sq c2 c3;
     wp_det_nonzero_iff_norm_nonzero :=
       wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero c2 c3;
     wp_right_inverse := fun z Hz =>
       proj1 (wedderburn_generalized_quaternion_two_sided_inverse c2 c3 z Hz);
     wp_left_inverse := fun z Hz =>
       proj2 (wedderburn_generalized_quaternion_two_sided_inverse c2 c3 z Hz) |}.

Definition wedderburn_coeff_elem (a b : R) : CDQuat :=
  mkQuat a b 0 0.

Definition wedderburn_affine_elem (a b : R) : CDQuat :=
  quat_add qj (wedderburn_coeff_elem a b).

Definition wedderburn_base_norm (c2 : R) (a b : R) : R :=
  a^2 - c2 * b^2.

Theorem wedderburn_affine_elem_coords :
  forall a b : R,
    wedderburn_affine_elem a b = mkQuat a b 1 0.
Proof.
  intros a b.
  unfold wedderburn_affine_elem, wedderburn_coeff_elem, quat_add, qj.
  simpl.
  f_equal; ring.
Qed.

Theorem wedderburn_generalized_coeff_norm :
  forall c2 c3 a b : R,
    dickson1921_param_norm c2 c3 (wedderburn_coeff_elem a b) =
    wedderburn_base_norm c2 a b.
Proof.
  intros c2 c3 a b.
  unfold wedderburn_coeff_elem, dickson1921_param_norm, wedderburn_base_norm.
  simpl.
  ring.
Qed.

Theorem wedderburn_generalized_affine_norm :
  forall c2 c3 a b : R,
    dickson1921_param_norm c2 c3 (wedderburn_affine_elem a b) =
    wedderburn_base_norm c2 a b - c3.
Proof.
  intros c2 c3 a b.
  unfold wedderburn_affine_elem, wedderburn_coeff_elem,
         dickson1921_param_norm, wedderburn_base_norm, quat_add, qj.
  simpl.
  ring.
Qed.

Theorem wedderburn_generalized_y_coeff_component :
  forall c2 c3 a b : R,
    dickson1921_param_mul c2 c3 qj (wedderburn_coeff_elem a (- b)) =
    mkQuat 0 0 a b.
Proof.
  intros c2 c3 a b.
  unfold dickson1921_param_mul, wedderburn_coeff_elem, qj.
  simpl.
  f_equal; ring.
Qed.

Theorem wedderburn_generalized_decomposition :
  forall c2 c3 a b c d : R,
    mkQuat a b c d =
    quat_add (wedderburn_coeff_elem a b)
      (dickson1921_param_mul c2 c3 qj (wedderburn_coeff_elem c (- d))).
Proof.
  intros c2 c3 a b c d.
  rewrite wedderburn_generalized_y_coeff_component.
  unfold wedderburn_coeff_elem, quat_add.
  simpl.
  f_equal; ring.
Qed.

Theorem wedderburn_generalized_decomposition_any :
  forall c2 c3 : R, forall q : CDQuat,
    exists a b c d : R,
      q = quat_add (wedderburn_coeff_elem a b)
            (dickson1921_param_mul c2 c3 qj (wedderburn_coeff_elem c (- d))).
Proof.
  intros c2 c3 [a b c d].
  exists a, b, c, d.
  exact (wedderburn_generalized_decomposition c2 c3 a b c d).
Qed.

Theorem wedderburn_generalized_coeff_det_nonzero_iff :
  forall c2 c3 a b : R,
    wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_coeff_elem a b) <> 0 <->
    wedderburn_base_norm c2 a b <> 0.
Proof.
  intros c2 c3 a b.
  rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
  rewrite wedderburn_generalized_coeff_norm.
  split.
  - intros Hdet Hn.
    apply Hdet.
    nra.
  - intros Hn Hdet.
    apply Hn.
    nra.
Qed.

Theorem wedderburn_generalized_affine_det_nonzero_iff :
  forall c2 c3 a b : R,
    wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) <> 0 <->
    wedderburn_base_norm c2 a b <> c3.
Proof.
  intros c2 c3 a b.
  rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
  rewrite wedderburn_generalized_affine_norm.
  split.
  - intros Hdet Hn.
    apply Hdet.
    nra.
  - intros Hn Hdet.
    apply Hn.
    nra.
Qed.

Theorem wedderburn_generalized_coeff_two_sided_inverse :
  forall c2 c3 a b : R,
    wedderburn_base_norm c2 a b <> 0 ->
    dickson1921_param_mul c2 c3 (wedderburn_coeff_elem a b)
      (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_coeff_elem a b)) = quat_one /\
    dickson1921_param_mul c2 c3
      (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_coeff_elem a b))
      (wedderburn_coeff_elem a b) = quat_one.
Proof.
  intros c2 c3 a b Hn.
  apply wedderburn_generalized_quaternion_two_sided_inverse.
  apply (proj2 (wedderburn_generalized_coeff_det_nonzero_iff c2 c3 a b)).
  exact Hn.
Qed.

Theorem wedderburn_generalized_affine_two_sided_inverse :
  forall c2 c3 a b : R,
    wedderburn_base_norm c2 a b <> c3 ->
    dickson1921_param_mul c2 c3 (wedderburn_affine_elem a b)
      (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_affine_elem a b)) = quat_one /\
    dickson1921_param_mul c2 c3
      (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_affine_elem a b))
      (wedderburn_affine_elem a b) = quat_one.
Proof.
  intros c2 c3 a b Hn.
  apply wedderburn_generalized_quaternion_two_sided_inverse.
  apply (proj2 (wedderburn_generalized_affine_det_nonzero_iff c2 c3 a b)).
  exact Hn.
Qed.

Theorem wedderburn_quaternion_affine_norm :
  forall a b : R,
    quat_norm_sq (wedderburn_affine_elem a b) = a^2 + b^2 + 1.
Proof.
  intros a b.
  unfold wedderburn_affine_elem, wedderburn_coeff_elem, quat_norm_sq, quat_add, qj.
  simpl.
  ring.
Qed.

Theorem wedderburn_quaternion_affine_always_invertible :
  forall a b : R,
    quat_mul (wedderburn_affine_elem a b) (quat_inv (wedderburn_affine_elem a b)) = quat_one /\
    quat_mul (quat_inv (wedderburn_affine_elem a b)) (wedderburn_affine_elem a b) = quat_one.
Proof.
  intros a b.
  apply wedderburn_quaternion_two_sided_inverse.
  intro Hdet.
  rewrite wedderburn_quaternion_det_equals_norm_sq in Hdet.
  rewrite wedderburn_quaternion_affine_norm in Hdet.
  nra.
Qed.

Theorem wedderburn_generalized_primitive_criterion_summary :
  (forall c2 c3 : R, forall q : CDQuat,
      exists a b c d : R,
        q = quat_add (wedderburn_coeff_elem a b)
              (dickson1921_param_mul c2 c3 qj (wedderburn_coeff_elem c (- d)))) /\
  (forall c2 c3 a b : R,
      wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_coeff_elem a b) <> 0 <->
      wedderburn_base_norm c2 a b <> 0) /\
  (forall c2 c3 a b : R,
      wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) <> 0 <->
      wedderburn_base_norm c2 a b <> c3) /\
  (forall c2 c3 a b : R,
      wedderburn_base_norm c2 a b <> 0 ->
      dickson1921_param_mul c2 c3 (wedderburn_coeff_elem a b)
        (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_coeff_elem a b)) = quat_one /\
      dickson1921_param_mul c2 c3
        (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_coeff_elem a b))
        (wedderburn_coeff_elem a b) = quat_one) /\
  (forall c2 c3 a b : R,
      wedderburn_base_norm c2 a b <> c3 ->
      dickson1921_param_mul c2 c3 (wedderburn_affine_elem a b)
        (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_affine_elem a b)) = quat_one /\
      dickson1921_param_mul c2 c3
        (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_affine_elem a b))
        (wedderburn_affine_elem a b) = quat_one).
Proof.
  split.
  - exact wedderburn_generalized_decomposition_any.
  - split.
    + exact wedderburn_generalized_coeff_det_nonzero_iff.
    + split.
      * exact wedderburn_generalized_affine_det_nonzero_iff.
      * split.
        -- exact wedderburn_generalized_coeff_two_sided_inverse.
        -- exact wedderburn_generalized_affine_two_sided_inverse.
Qed.

Definition wedderburn_base_norm_represents (c2 target : R) : Prop :=
  exists a b : R, wedderburn_base_norm c2 a b = target.

Theorem wedderburn_generalized_affine_singular_iff_base_norm_represents :
  forall c2 c3 : R,
    (exists a b : R,
        wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) = 0) <->
    wedderburn_base_norm_represents c2 c3.
Proof.
  intros c2 c3.
  split.
  - intros [a [b Hdet]].
    exists a, b.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq in Hdet.
    rewrite wedderburn_generalized_affine_norm in Hdet.
    nra.
  - intros [a [b Hab]].
    exists a, b.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq.
    rewrite wedderburn_generalized_affine_norm.
    nra.
Qed.

Theorem wedderburn_generalized_affine_nonrepresentation_iff_all_det_nonzero :
  forall c2 c3 : R,
    ~ wedderburn_base_norm_represents c2 c3 <->
    forall a b : R,
      wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) <> 0.
Proof.
  intros c2 c3.
  split.
  - intros Hnot a b.
    apply (proj2 (wedderburn_generalized_affine_det_nonzero_iff c2 c3 a b)).
    intro Hab.
    apply Hnot.
    exists a, b.
    exact Hab.
  - intros Hall Hrep.
    destruct (proj2 (wedderburn_generalized_affine_singular_iff_base_norm_represents c2 c3) Hrep)
      as [a [b Hdet]].
    apply (Hall a b).
    exact Hdet.
Qed.

Theorem wedderburn_generalized_affine_all_invertible_if_not_base_norm :
  forall c2 c3 : R,
    ~ wedderburn_base_norm_represents c2 c3 ->
    forall a b : R,
      dickson1921_param_mul c2 c3 (wedderburn_affine_elem a b)
        (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_affine_elem a b)) = quat_one /\
      dickson1921_param_mul c2 c3
        (wedderburn_generalized_quaternion_inv c2 c3 (wedderburn_affine_elem a b))
        (wedderburn_affine_elem a b) = quat_one.
Proof.
  intros c2 c3 Hnot a b.
  apply wedderburn_generalized_affine_two_sided_inverse.
  intro Hab.
  apply Hnot.
  exists a, b.
  exact Hab.
Qed.

Theorem wedderburn_quaternion_neg_one_not_base_norm :
  ~ wedderburn_base_norm_represents (-1) (-1).
Proof.
  intros [a [b Hab]].
  unfold wedderburn_base_norm in Hab.
  nra.
Qed.

Theorem wedderburn_quaternion_affine_always_invertible_section2 :
  forall a b : R,
    quat_mul (wedderburn_affine_elem a b) (quat_inv (wedderburn_affine_elem a b)) = quat_one /\
    quat_mul (quat_inv (wedderburn_affine_elem a b)) (wedderburn_affine_elem a b) = quat_one.
Proof.
  intros a b.
  apply wedderburn_quaternion_affine_always_invertible.
Qed.

Record WedderburnSection2QuaternionSurface (c2 c3 : R) := {
  ws2_primitive_surface : WedderburnPrimitiveN2Surface CDQuat;
  ws2_decomposition_any :
    forall q : CDQuat,
      exists a b d e : R,
        q = quat_add (wedderburn_coeff_elem a b)
              (dickson1921_param_mul c2 c3 qj (wedderburn_coeff_elem d (- e)));
  ws2_coeff_det_criterion :
    forall a b : R,
      wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_coeff_elem a b) <> 0 <->
      wedderburn_base_norm c2 a b <> 0;
  ws2_affine_det_criterion :
    forall a b : R,
      wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) <> 0 <->
      wedderburn_base_norm c2 a b <> c3;
  ws2_affine_singular_criterion :
    (exists a b : R,
        wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) = 0) <->
    wedderburn_base_norm_represents c2 c3;
  ws2_affine_nonrepresentation_criterion :
    ~ wedderburn_base_norm_represents c2 c3 <->
    forall a b : R,
      wedderburn_generalized_quaternion_left_det c2 c3 (wedderburn_affine_elem a b) <> 0;
}.

Definition wedderburn_generalized_section2_surface
    (c2 c3 : R) : WedderburnSection2QuaternionSurface c2 c3 :=
  {| ws2_primitive_surface :=
       wedderburn_generalized_quaternion_primitive_surface c2 c3;
     ws2_decomposition_any := wedderburn_generalized_decomposition_any c2 c3;
     ws2_coeff_det_criterion := wedderburn_generalized_coeff_det_nonzero_iff c2 c3;
     ws2_affine_det_criterion := wedderburn_generalized_affine_det_nonzero_iff c2 c3;
     ws2_affine_singular_criterion :=
       wedderburn_generalized_affine_singular_iff_base_norm_represents c2 c3;
     ws2_affine_nonrepresentation_criterion :=
       wedderburn_generalized_affine_nonrepresentation_iff_all_det_nonzero c2 c3 |}.

Definition wedderburn_base_norm_anisotropic (c2 : R) : Prop :=
  forall a b : R, wedderburn_base_norm c2 a b = 0 -> a = 0 /\ b = 0.

Theorem wedderburn_base_norm_opp_right :
  forall c2 a b : R,
    wedderburn_base_norm c2 a (- b) = wedderburn_base_norm c2 a b.
Proof.
  intros c2 a b.
  unfold wedderburn_base_norm.
  ring.
Qed.

Theorem wedderburn_base_norm_nonzero_of_anisotropic :
  forall c2 a b : R,
    wedderburn_base_norm_anisotropic c2 ->
    a <> 0 \/ b <> 0 ->
    wedderburn_base_norm c2 a b <> 0.
Proof.
  intros c2 a b Hani Hnz Hzero.
  destruct (Hani a b Hzero) as [Ha Hb].
  destruct Hnz as [Ha' | Hb']; contradiction.
Qed.

Theorem wedderburn_generalized_nonzero_tail_factorization :
  forall c2 c3 a b c d : R,
    wedderburn_base_norm c2 c d <> 0 ->
    mkQuat a b c d =
    dickson1921_param_mul c2 c3
      (wedderburn_affine_elem
        ((a * c + c2 * b * d) / wedderburn_base_norm c2 c d)
        ((a * d + b * c) / wedderburn_base_norm c2 c d))
      (wedderburn_coeff_elem c (- d)).
Proof.
  intros c2 c3 a b c d Hden.
  unfold wedderburn_affine_elem, wedderburn_coeff_elem, quat_add, qj.
  unfold dickson1921_param_mul, wedderburn_base_norm.
  simpl.
  unfold wedderburn_base_norm in Hden.
  assert (Hden' : c * c - c2 * (d * d) <> 0).
  {
    intro Habs.
    apply Hden.
    nra.
  }
  f_equal.
  - field; exact Hden'.
  - field; exact Hden'.
  - ring.
  - ring.
Qed.

Theorem wedderburn_generalized_nonzero_det_nonzero :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_base_norm_anisotropic c2 ->
    ~ wedderburn_base_norm_represents c2 c3 ->
    q <> quat_zero ->
    wedderburn_generalized_quaternion_left_det c2 c3 q <> 0.
Proof.
  intros c2 c3 [a b c d] Hani Hnrep Hnz.
  destruct (Req_EM_T c 0) as [Hc|Hc];
  destruct (Req_EM_T d 0) as [Hd|Hd].
  - subst c d.
    apply (proj2 (wedderburn_generalized_coeff_det_nonzero_iff c2 c3 a b)).
    apply wedderburn_base_norm_nonzero_of_anisotropic; [exact Hani|].
    destruct (Req_EM_T a 0) as [Ha|Ha];
    destruct (Req_EM_T b 0) as [Hb|Hb].
    + subst a b. exfalso. apply Hnz. reflexivity.
    + right; exact Hb.
    + left; exact Ha.
    + left; exact Ha.
  - assert (Htail : c <> 0 \/ d <> 0) by (right; exact Hd).
    assert (Hden : wedderburn_base_norm c2 c d <> 0).
    {
      apply wedderburn_base_norm_nonzero_of_anisotropic; [exact Hani|exact Htail].
    }
    set (alpha := (a * c + c2 * b * d) / wedderburn_base_norm c2 c d).
    set (beta := (a * d + b * c) / wedderburn_base_norm c2 c d).
    assert (Hfac :
      mkQuat a b c d =
      dickson1921_param_mul c2 c3 (wedderburn_affine_elem alpha beta)
        (wedderburn_coeff_elem c (- d))).
    {
      unfold alpha, beta.
      exact (wedderburn_generalized_nonzero_tail_factorization c2 c3 a b c d Hden).
    }
    rewrite Hfac.
    pose proof
      ((proj1 (wedderburn_generalized_affine_nonrepresentation_iff_all_det_nonzero c2 c3))
         Hnrep alpha beta) as Haff_det.
    pose proof
      ((proj1 (wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero
         c2 c3 (wedderburn_affine_elem alpha beta))) Haff_det) as Haff_norm.
    assert (Hcoeff_det :
      wedderburn_generalized_quaternion_left_det c2 c3
        (wedderburn_coeff_elem c (- d)) <> 0).
    {
      apply (proj2 (wedderburn_generalized_coeff_det_nonzero_iff c2 c3 c (- d))).
      rewrite wedderburn_base_norm_opp_right.
      exact Hden.
    }
    pose proof
      ((proj1 (wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero
         c2 c3 (wedderburn_coeff_elem c (- d)))) Hcoeff_det) as Hcoeff_norm.
    intro Hdet.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq in Hdet.
    rewrite dickson1921_param_norm_mul in Hdet.
    assert (Hprod :
      dickson1921_param_norm c2 c3 (wedderburn_affine_elem alpha beta) *
      dickson1921_param_norm c2 c3 (wedderburn_coeff_elem c (- d)) = 0).
    { nra. }
    apply Haff_norm.
    nra.
  - assert (Htail : c <> 0 \/ d <> 0) by (left; exact Hc).
    assert (Hden : wedderburn_base_norm c2 c d <> 0).
    {
      apply wedderburn_base_norm_nonzero_of_anisotropic; [exact Hani|exact Htail].
    }
    set (alpha := (a * c + c2 * b * d) / wedderburn_base_norm c2 c d).
    set (beta := (a * d + b * c) / wedderburn_base_norm c2 c d).
    assert (Hfac :
      mkQuat a b c d =
      dickson1921_param_mul c2 c3 (wedderburn_affine_elem alpha beta)
        (wedderburn_coeff_elem c (- d))).
    {
      unfold alpha, beta.
      exact (wedderburn_generalized_nonzero_tail_factorization c2 c3 a b c d Hden).
    }
    rewrite Hfac.
    pose proof
      ((proj1 (wedderburn_generalized_affine_nonrepresentation_iff_all_det_nonzero c2 c3))
         Hnrep alpha beta) as Haff_det.
    pose proof
      ((proj1 (wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero
         c2 c3 (wedderburn_affine_elem alpha beta))) Haff_det) as Haff_norm.
    assert (Hcoeff_det :
      wedderburn_generalized_quaternion_left_det c2 c3
        (wedderburn_coeff_elem c (- d)) <> 0).
    {
      apply (proj2 (wedderburn_generalized_coeff_det_nonzero_iff c2 c3 c (- d))).
      rewrite wedderburn_base_norm_opp_right.
      exact Hden.
    }
    pose proof
      ((proj1 (wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero
         c2 c3 (wedderburn_coeff_elem c (- d)))) Hcoeff_det) as Hcoeff_norm.
    intro Hdet.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq in Hdet.
    rewrite dickson1921_param_norm_mul in Hdet.
    assert (Hprod :
      dickson1921_param_norm c2 c3 (wedderburn_affine_elem alpha beta) *
      dickson1921_param_norm c2 c3 (wedderburn_coeff_elem c (- d)) = 0).
    { nra. }
    apply Haff_norm.
    nra.
  - assert (Htail : c <> 0 \/ d <> 0) by (left; exact Hc).
    assert (Hden : wedderburn_base_norm c2 c d <> 0).
    {
      apply wedderburn_base_norm_nonzero_of_anisotropic; [exact Hani|exact Htail].
    }
    set (alpha := (a * c + c2 * b * d) / wedderburn_base_norm c2 c d).
    set (beta := (a * d + b * c) / wedderburn_base_norm c2 c d).
    assert (Hfac :
      mkQuat a b c d =
      dickson1921_param_mul c2 c3 (wedderburn_affine_elem alpha beta)
        (wedderburn_coeff_elem c (- d))).
    {
      unfold alpha, beta.
      exact (wedderburn_generalized_nonzero_tail_factorization c2 c3 a b c d Hden).
    }
    rewrite Hfac.
    pose proof
      ((proj1 (wedderburn_generalized_affine_nonrepresentation_iff_all_det_nonzero c2 c3))
         Hnrep alpha beta) as Haff_det.
    pose proof
      ((proj1 (wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero
         c2 c3 (wedderburn_affine_elem alpha beta))) Haff_det) as Haff_norm.
    assert (Hcoeff_det :
      wedderburn_generalized_quaternion_left_det c2 c3
        (wedderburn_coeff_elem c (- d)) <> 0).
    {
      apply (proj2 (wedderburn_generalized_coeff_det_nonzero_iff c2 c3 c (- d))).
      rewrite wedderburn_base_norm_opp_right.
      exact Hden.
    }
    pose proof
      ((proj1 (wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero
         c2 c3 (wedderburn_coeff_elem c (- d)))) Hcoeff_det) as Hcoeff_norm.
    intro Hdet.
    rewrite wedderburn_generalized_quaternion_det_equals_norm_sq in Hdet.
    rewrite dickson1921_param_norm_mul in Hdet.
    assert (Hprod :
      dickson1921_param_norm c2 c3 (wedderburn_affine_elem alpha beta) *
      dickson1921_param_norm c2 c3 (wedderburn_coeff_elem c (- d)) = 0).
    { nra. }
    apply Haff_norm.
    nra.
Qed.

Theorem wedderburn_generalized_nonzero_two_sided_inverse :
  forall c2 c3 : R, forall q : CDQuat,
    wedderburn_base_norm_anisotropic c2 ->
    ~ wedderburn_base_norm_represents c2 c3 ->
    q <> quat_zero ->
    dickson1921_param_mul c2 c3 q
      (wedderburn_generalized_quaternion_inv c2 c3 q) = quat_one /\
    dickson1921_param_mul c2 c3
      (wedderburn_generalized_quaternion_inv c2 c3 q) q = quat_one.
Proof.
  intros c2 c3 q Hani Hnrep Hnz.
  apply wedderburn_generalized_quaternion_two_sided_inverse.
  exact (wedderburn_generalized_nonzero_det_nonzero c2 c3 q Hani Hnrep Hnz).
Qed.

Theorem wedderburn_quaternion_base_norm_anisotropic :
  wedderburn_base_norm_anisotropic (-1).
Proof.
  intros a b Hzero.
  unfold wedderburn_base_norm in Hzero.
  nra.
Qed.

Theorem wedderburn_quaternion_every_nonzero_two_sided_inverse_param :
  forall q : CDQuat,
    q <> quat_zero ->
    dickson1921_param_mul (-1) (-1) q
      (wedderburn_generalized_quaternion_inv (-1) (-1) q) = quat_one /\
    dickson1921_param_mul (-1) (-1)
      (wedderburn_generalized_quaternion_inv (-1) (-1) q) q = quat_one.
Proof.
  intros q Hnz.
  apply wedderburn_generalized_nonzero_two_sided_inverse.
  - exact wedderburn_quaternion_base_norm_anisotropic.
  - exact wedderburn_quaternion_neg_one_not_base_norm.
  - exact Hnz.
Qed.

Theorem wedderburn_quaternion_every_nonzero_two_sided_inverse :
  forall q : CDQuat,
    q <> quat_zero ->
    quat_mul q (quat_inv q) = quat_one /\
    quat_mul (quat_inv q) q = quat_one.
Proof.
  intros q Hnz.
  apply wedderburn_quaternion_two_sided_inverse.
  intro Hdet.
  apply Hnz.
  destruct q as [a b c d].
  unfold quat_zero.
  rewrite wedderburn_quaternion_det_equals_norm_sq in Hdet.
  unfold quat_norm_sq in Hdet.
  simpl in Hdet.
  assert (Hsum : a * a + b * b + c * c + d * d = 0) by nra.
  assert (Ha : a = 0) by nra.
  assert (Hb : b = 0) by nra.
  assert (Hc : c = 0) by nra.
  assert (Hd : d = 0) by nra.
  subst.
  reflexivity.
Qed.

Record WedderburnSection2DivisionSurface (c2 c3 : R) := {
  wsd_section2_surface : WedderburnSection2QuaternionSurface c2 c3;
  wsd_base_norm_anisotropic : wedderburn_base_norm_anisotropic c2;
  wsd_nonrepresentation : ~ wedderburn_base_norm_represents c2 c3;
  wsd_all_nonzero_det :
    forall q : CDQuat,
      q <> quat_zero ->
      wedderburn_generalized_quaternion_left_det c2 c3 q <> 0;
  wsd_all_nonzero_two_sided_inverse :
    forall q : CDQuat,
      q <> quat_zero ->
      dickson1921_param_mul c2 c3 q
        (wedderburn_generalized_quaternion_inv c2 c3 q) = quat_one /\
      dickson1921_param_mul c2 c3
        (wedderburn_generalized_quaternion_inv c2 c3 q) q = quat_one;
}.

Definition wedderburn_generalized_division_surface
    (c2 c3 : R)
    (Hani : wedderburn_base_norm_anisotropic c2)
    (Hnrep : ~ wedderburn_base_norm_represents c2 c3)
    : WedderburnSection2DivisionSurface c2 c3 :=
  {| wsd_section2_surface := wedderburn_generalized_section2_surface c2 c3;
     wsd_base_norm_anisotropic := Hani;
     wsd_nonrepresentation := Hnrep;
     wsd_all_nonzero_det := fun q Hq =>
       wedderburn_generalized_nonzero_det_nonzero c2 c3 q Hani Hnrep Hq;
     wsd_all_nonzero_two_sided_inverse := fun q Hq =>
       wedderburn_generalized_nonzero_two_sided_inverse c2 c3 q Hani Hnrep Hq |}.

Definition wedderburn_quaternion_division_surface :
    WedderburnSection2DivisionSurface (-1) (-1) :=
  wedderburn_generalized_division_surface
    (-1) (-1)
    wedderburn_quaternion_base_norm_anisotropic
    wedderburn_quaternion_neg_one_not_base_norm.

Theorem wedderburn_generalized_quaternion_surface_summary :
  (forall c2 c3 : R,
      dickson1921_param_mul c2 c3 qi qj =
      dickson1921_param_mul c2 c3 qj (quat_conj qi)) /\
  (forall c2 c3 : R,
      dickson1921_param_mul c2 c3 qj qj = quat_scale c3 quat_one) /\
  (forall c2 c3 : R,
      c2 <> 0 ->
      c3 <> 0 ->
      qk = dickson1921_param_mul c2 c3 qi qj /\
      qi = quat_scale (- / c3) (dickson1921_param_mul c2 c3 qj qk) /\
      qj = quat_scale (- / c2) (dickson1921_param_mul c2 c3 qk qi)) /\
  (forall c2 c3 : R, forall q : CDQuat,
      wedderburn_generalized_quaternion_left_det c2 c3 q =
      (dickson1921_param_norm c2 c3 q)^2) /\
  (forall c2 c3 : R, forall q : CDQuat,
      wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 <->
      dickson1921_param_norm c2 c3 q <> 0) /\
  (forall c2 c3 : R, forall q : CDQuat,
      wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 ->
      exists r : CDQuat, dickson1921_param_mul c2 c3 q r = quat_one) /\
  (forall c2 c3 : R, forall q : CDQuat,
      wedderburn_generalized_quaternion_left_det c2 c3 q <> 0 ->
      exists l : CDQuat, dickson1921_param_mul c2 c3 l q = quat_one).
Proof.
  split.
  - exact wedderburn_generalized_quaternion_cyclic_relation.
  - split.
    + exact wedderburn_generalized_quaternion_y_square.
    + split.
      * exact wedderburn_generalized_quaternion_cyclic_generation.
      * split.
        -- exact wedderburn_generalized_quaternion_det_equals_norm_sq.
        -- split.
           ++ exact wedderburn_generalized_quaternion_det_nonzero_iff_norm_nonzero.
           ++ split.
              ** exact wedderburn_generalized_quaternion_det_implies_right_inverse.
              ** exact wedderburn_generalized_quaternion_det_implies_left_inverse.
Qed.
