//! Catalog parsers for cosmological and astrophysical datasets.
//!
//! Each module provides:
//! - Download URLs and metadata
//! - A DatasetProvider implementation for fetching
//! - Typed record structs with CSV parsing

pub mod ace_mag;
#[cfg(feature = "fetch")]
pub mod ace_mag_fetch;
pub mod aflow;
#[cfg(feature = "fetch")]
pub mod aflow_fetch;
pub mod atnf;
pub mod bepicolombo;
#[cfg(feature = "fetch")]
pub mod bepicolombo_fetch;
pub mod bl_filterbank;
pub mod cassini;
#[cfg(feature = "fetch")]
pub mod cassini_fetch;
pub mod chime;
pub mod cluster;
#[cfg(feature = "fetch")]
pub mod cluster_fetch;
pub mod des_y6;
pub mod desi_bao;
pub mod eht;
pub mod fermi_gbm;
pub mod gaia;
pub mod gaia_mw_rotation;
pub mod gwtc;
pub mod helios;
#[cfg(feature = "fetch")]
pub mod helios_fetch;
pub mod hi_cube;
pub mod hic_raa;
pub mod hipparcos;
pub mod hst;
#[cfg(feature = "fetch")]
pub mod hst_fetch;
pub mod ibex;
#[cfg(feature = "fetch")]
pub mod ibex_fetch;
pub mod imap;
#[cfg(feature = "fetch")]
pub mod imap_fetch;
pub mod imp8;
#[cfg(feature = "fetch")]
pub mod imp8_fetch;
pub mod intermagnet;
pub mod jarvis;
#[cfg(feature = "fetch")]
pub mod jarvis_fetch;
pub mod juno;
#[cfg(feature = "fetch")]
pub mod juno_fetch;
pub mod jwst;
#[cfg(feature = "fetch")]
pub mod jwst_fetch;
pub mod landsat;
#[cfg(feature = "fits")]
pub mod lotss;
pub mod manga;
pub(crate) mod mast_public_metadata;
pub mod maven_mag;
#[cfg(feature = "fetch")]
pub mod maven_mag_fetch;
pub mod mcgill;
pub mod messenger;
#[cfg(feature = "fetch")]
pub mod messenger_fetch;
pub mod mms;
pub mod nanograv;
pub mod new_horizons;
#[cfg(feature = "fetch")]
pub mod new_horizons_fetch;
pub mod omni;
#[cfg(feature = "fetch")]
pub mod omni_fetch;
pub mod pantheon;
pub mod pdg;
pub mod pioneer;
#[cfg(feature = "fetch")]
pub mod pioneer_fetch;
pub mod planck;
pub mod psp;
#[cfg(feature = "fetch")]
pub mod psp_fetch;
pub mod psp_fields;
#[cfg(feature = "fetch")]
pub mod psp_fields_fetch;
pub mod psp_spc;
#[cfg(feature = "fetch")]
pub mod psp_spc_fetch;
pub mod psp_spi;
#[cfg(feature = "fetch")]
pub mod psp_spi_fetch;
pub mod psp_sqtn;
#[cfg(feature = "fetch")]
pub mod psp_sqtn_fetch;
pub mod rosetta;
pub mod sdo_hmi;
pub mod sdss;
pub mod soho_celias;
pub mod solar_orbiter;
#[cfg(feature = "fetch")]
pub mod solar_orbiter_fetch;
pub mod solar_orbiter_mag;
pub mod solar_orbiter_rpw;
#[cfg(feature = "fetch")]
pub mod solar_orbiter_rpw_fetch;
pub mod solar_orbiter_rpw_density;
pub mod solar_orbiter_rpw_hfr;
#[cfg(feature = "fetch")]
pub mod solar_orbiter_rpw_hfr_fetch;
pub mod solar_orbiter_rpw_tnr;
#[cfg(feature = "fetch")]
pub mod solar_orbiter_rpw_tnr_fetch;
pub mod solar_orbiter_swa;
#[cfg(feature = "fetch")]
pub mod solar_orbiter_swa_fetch;
pub mod solar_wind;
#[cfg(feature = "fetch")]
pub mod solar_wind_fetch;
pub mod sorce;
pub mod sparc;
pub mod spdf_fleet;
pub mod spdf_merged;
pub mod stereo_plastic;
#[cfg(feature = "fetch")]
pub mod stereo_plastic_fetch;
pub mod swarm_mag;
pub mod themis;
#[cfg(feature = "fetch")]
pub mod themis_fetch;
pub mod things;
#[cfg(feature = "fetch")]
pub mod things_fetch;
pub mod tsi;
pub mod ulysses;
#[cfg(feature = "fetch")]
pub mod ulysses_fetch;
pub mod union3;
pub mod voyager;
#[cfg(feature = "fetch")]
pub mod voyager_fetch;
pub mod voyager_crs;
pub mod voyager_crs_flux;
pub mod voyager_pws;
pub mod wind_swe;
#[cfg(feature = "fetch")]
pub mod wind_swe_fetch;
pub mod wow;

pub use eht::{list_tgz_members, tgz_member_count, validate_eht_archive};
pub use hipparcos::{
    HIPPARCOS_EXPECTED_ROWS, HIPPARCOS_LINE_WIDTH, HIPPARCOS_PIPE_COUNT, parse_hip_number,
    validate_hipparcos_format,
};
pub use landsat::{count_stac_assets, extract_cloud_cover, validate_stac_schema};
pub use tsi::{TsiOverlapResult, compare_tsis_sorce};
