"""
Golden contract tests for registry-emit output formats.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_EMIT_BIN = REPO_ROOT / "target" / "debug" / "registry-emit"


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        [str(REGISTRY_EMIT_BIN), *cmd],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, (
        f"registry-emit failed for {' '.join(cmd)}\n"
        f"stdout:\n{proc.stdout}\n"
        f"stderr:\n{proc.stderr}"
    )
    return proc


def test_registry_emit_bibliography_bibtex_contract(tmp_path: Path) -> None:
    build = subprocess.run(
        ["cargo", "build", "--quiet", "--bin", "registry-emit"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert build.returncode == 0, f"cargo build failed:\n{build.stdout}\n{build.stderr}"
    assert REGISTRY_EMIT_BIN.exists()

    input_path = tmp_path / "bibliography.toml"
    output_path = tmp_path / "bibliography.bib"
    input_path.write_text(
        dedent(
            """
            [[entry]]
            id = "B-001"
            citation_markdown = "**Doe, J.** *Test Title* (2024)"
            section = "physics"
            urls = ["https://example.com/paper"]
            dois = ["10.1234/test"]
            notes = ["n1", "n2"]
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )

    proc = _run(
        [
            "bibliography-bibtex",
            "--input",
            str(input_path),
            "--output",
            str(output_path),
        ]
    )
    assert "Emitted BibTeX bibliography" in proc.stdout

    expected = (
        "% Auto-generated by registry-emit bibliography-bibtex\n"
        "% Source of truth: registry/bibliography.toml\n"
        "\n"
        "@misc{b_001,\n"
        "  author = {Doe, J.},\n"
        "  title = {Test Title},\n"
        "  year = {2024},\n"
        "  keywords = {physics},\n"
        "  doi = {10.1234/test},\n"
        "  url = {https://example.com/paper},\n"
        "  note = {n1 | n2},\n"
        "}\n"
        "\n"
    )
    assert output_path.read_text(encoding="utf-8") == expected


def test_registry_emit_equations_tex_contract(tmp_path: Path) -> None:
    input_path = tmp_path / "equation_atoms.toml"
    output_path = tmp_path / "equations.tex"
    input_path.write_text(
        dedent(
            """
            [[atom]]
            id = "EQ-002"
            expression = "a + b = c"
            source_path = "src/equations.rs"
            source_line = 7
            domain_hint = "optics"

            [[atom]]
            id = "EQ-001"
            expression = "x^2 + y^2 = z^2"
            source_path = "src/equations.rs"
            source_line = 42
            domain_hint = "algebra"
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )

    proc = _run(
        [
            "equations-tex",
            "--input",
            str(input_path),
            "--output",
            str(output_path),
            "--domain",
            "algebra",
        ]
    )
    assert "Emitted TeX equation report" in proc.stdout

    expected = (
        "% Auto-generated by registry-emit equations-tex\n"
        "% Source of truth: registry/knowledge/equation_atoms.toml\n"
        "\n"
        "\\section*{Equation Atoms}\\label{sec:equation-atoms}\n"
        "\n"
        "\\subsection*{EQ-001 (algebra)}\n"
        "\\[\n"
        "x^2 + y^2 = z^2\n"
        "\\]\n"
        "\\noindent\\texttt{Source: src/equations.rs:42}\n"
        "\n"
    )
    assert output_path.read_text(encoding="utf-8") == expected


def test_registry_emit_dataset_pgfplots_contract(tmp_path: Path) -> None:
    input_path = tmp_path / "dataset.toml"
    output_path = tmp_path / "plot.tex"
    input_path.write_text(
        dedent(
            """
            [dataset]
            id = "DS-001"
            source_csv = "data/csv/demo.csv"
            header = ["t", "value", "label"]
            rows = [
              ["0", "1.25", "a"],
              ["1", "2.50", "b"],
              ["2", "3.75", "c"],
            ]
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )

    proc = _run(
        [
            "dataset-pgfplots",
            "--input",
            str(input_path),
            "--output",
            str(output_path),
            "--x-col",
            "t",
            "--y-col",
            "value",
        ]
    )
    assert "Emitted PGFPlots" in proc.stdout

    expected = (
        "% Auto-generated by registry-emit dataset-pgfplots\n"
        f"% Source dataset TOML: {input_path}\n"
        "% Source CSV: data/csv/demo.csv\n"
        "\n"
        "\\begin{tikzpicture}\n"
        "\\begin{axis}[\n"
        "  title={DS-001},\n"
        "  xlabel={t},\n"
        "  ylabel={value},\n"
        "  grid=both,\n"
        "]\n"
        "\\addplot+[mark=none] coordinates {\n"
        "  (0.000000000000, 1.250000000000)\n"
        "  (1.000000000000, 2.500000000000)\n"
        "  (2.000000000000, 3.750000000000)\n"
        "};\n"
        "\\end{axis}\n"
        "\\end{tikzpicture}\n"
    )
    assert output_path.read_text(encoding="utf-8") == expected


def test_registry_emit_mermaid_contract(tmp_path: Path) -> None:
    input_path = tmp_path / "diagram.toml"
    output_path = tmp_path / "diagram.mmd"
    input_path.write_text(
        dedent(
            """
            [diagram]
            kind = "flowchart"
            direction = "LR"
            title = "Demo Flow"

            [[node]]
            id = "A"
            label = "Start"

            [[node]]
            id = "B"

            [[edge]]
            from = "A"
            to = "B"
            label = "go"
            style = "dotted"
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )

    proc = _run(
        [
            "mermaid",
            "--input",
            str(input_path),
            "--output",
            str(output_path),
        ]
    )
    assert "Emitted Mermaid diagram" in proc.stdout

    expected = (
        "%% Auto-generated by registry-emit mermaid\n"
        f"%% Source TOML: {input_path}\n"
        "---\n"
        "title: Demo Flow\n"
        "---\n"
        "\n"
        "flowchart LR\n"
        "  A[\"Start\"]\n"
        "  B[\"B\"]\n"
        "  A -.->|go| B\n"
    )
    assert output_path.read_text(encoding="utf-8") == expected


def test_registry_emit_svg_contract(tmp_path: Path) -> None:
    input_path = tmp_path / "vector.toml"
    output_path = tmp_path / "vector.svg"
    input_path.write_text(
        dedent(
            """
            [svg]
            width = 100
            height = 80
            background = "#000000"

            [[rect]]
            x = 10
            y = 12
            width = 20
            height = 30
            fill = "#111111"

            [[line]]
            x1 = 0
            y1 = 0
            x2 = 10
            y2 = 10

            [[circle]]
            cx = 50
            cy = 40
            r = 5

            [[path]]
            d = "M0 0 L10 10"
            stroke = "#00ff00"

            [[text]]
            x = 5
            y = 70
            value = "Hi & Bye"
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )

    proc = _run(
        [
            "svg",
            "--input",
            str(input_path),
            "--output",
            str(output_path),
        ]
    )
    assert "Emitted SVG" in proc.stdout

    expected = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<!-- Auto-generated by registry-emit svg -->\n"
        f"<!-- Source TOML: {input_path} -->\n"
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"100\" height=\"80\" "
        "viewBox=\"0 0 100 80\">\n"
        "  <rect x=\"0\" y=\"0\" width=\"100\" height=\"80\" fill=\"#000000\" />\n"
        "  <rect x=\"10.000000\" y=\"12.000000\" width=\"20.000000\" "
        "height=\"30.000000\" fill=\"#111111\" stroke=\"none\" "
        "stroke-width=\"0.000000\" rx=\"0.000000\" ry=\"0.000000\" />\n"
        "  <line x1=\"0.000000\" y1=\"0.000000\" x2=\"10.000000\" y2=\"10.000000\" "
        "stroke=\"#ffffff\" stroke-width=\"1.000000\" />\n"
        "  <circle cx=\"50.000000\" cy=\"40.000000\" r=\"5.000000\" fill=\"none\" "
        "stroke=\"none\" stroke-width=\"0.000000\" />\n"
        "  <path d=\"M0 0 L10 10\" fill=\"none\" stroke=\"#00ff00\" stroke-width=\"1.000000\" />\n"
        "  <text x=\"5.000000\" y=\"70.000000\" fill=\"#ffffff\" font-size=\"12.000000\" "
        "font-family=\"sans-serif\">Hi &amp; Bye</text>\n"
        "</svg>\n"
    )
    assert output_path.read_text(encoding="utf-8") == expected
