//! Compatibility-TOML renderers for the three planning lanes:
//! roadmap, todo (action items), and next-actions.
//!
//! Each rendered TOML is a deterministic compatibility export
//! generated from the canonical control-plane SQLite database. The
//! rendered text matches the format the legacy hand-maintained TOML
//! used so that downstream readers (Cargo, registry-audit tools,
//! markdown converters) continue to parse it without modification.
//!
//! Methods added to `ProvenanceStore` via a second `impl` block:
//!   * `render_roadmap_compat_toml`
//!   * `render_todo_compat_toml`
//!   * `render_next_actions_compat_toml`
//!
//! These are `pub(super)` so the parent's `render_planning_compat_toml`
//! dispatcher can call them. Each fn:
//!   1. Loads the registry snapshot for the lane via
//!      `self.parse_registry_snapshot(kind)` (private parent fn)
//!   2. Loads the row collection via
//!      `self.planning_{roadmap, todo, next_action}_rows()` (pub
//!      methods on the parent)
//!   3. Builds a `Vec<String>` of rendered lines using the
//!      `toml_helpers` compat-* helpers
//!   4. Trims trailing blank lines and joins with "\n"

use anyhow::Result;

use crate::{
    ProvenanceStore,
    toml_helpers::{
        compat_child_table, compat_json_string_array, compat_root_table, compat_table_array,
        compat_table_bool, compat_table_string, compat_toml_quote, compat_toml_string_array,
        trim_trailing_blank_lines,
    },
};

impl ProvenanceStore {
    pub(crate) fn render_roadmap_compat_toml(&self) -> Result<String> {
        let snapshot = self.parse_registry_snapshot("roadmap")?;
        let roadmap_table = snapshot
            .as_ref()
            .and_then(|value| compat_root_table(value, "roadmap"));
        let schema_table = compat_child_table(roadmap_table, "schema");
        let sections_table = compat_child_table(roadmap_table, "sections");
        let rows = self.planning_roadmap_rows()?;
        let status_allowlist = compat_table_array(
            roadmap_table,
            "status_allowlist",
            &[
                "planned",
                "active",
                "in_progress",
                "done",
                "paused",
                "blocked",
            ],
        );
        let priority_allowlist = compat_table_array(
            roadmap_table,
            "priority_allowlist",
            &["high", "medium", "low"],
        );
        let required_fields = compat_table_array(
            schema_table,
            "required_fields",
            &[
                "id",
                "name",
                "priority",
                "status",
                "status_token",
                "description",
                "dependencies",
                "acceptance_criteria",
            ],
        );

        let mut lines = vec![
            "# GENERATED VIEW: DO NOT EDIT.".to_string(),
            "# Update via `gororoba-db planning ...` against `registry/canonical/control_plane.sqlite3`.".to_string(),
            "# Operational roadmap registry (SQLite compatibility export from canonical control_plane.sqlite3).".to_string(),
            "# Generated by `gororoba-db build` / `gororoba-db export-planning --table roadmap`.".to_string(),
            String::new(),
            "[roadmap]".to_string(),
            format!(
                "source_markdown = {}",
                compat_toml_quote(&compat_table_string(
                    roadmap_table,
                    "source_markdown",
                    "docs/ROADMAP.md",
                ))
            ),
            format!(
                "consolidated_date = {}",
                compat_toml_quote(&compat_table_string(
                    roadmap_table,
                    "consolidated_date",
                    "2026-02-10",
                ))
            ),
            format!(
                "supersedes = {}",
                compat_toml_string_array(&compat_table_array(roadmap_table, "supersedes", &[]))
            ),
            format!(
                "companion_docs = {}",
                compat_toml_string_array(&compat_table_array(
                    roadmap_table,
                    "companion_docs",
                    &[]
                ))
            ),
            format!(
                "status = {}",
                compat_toml_quote(&compat_table_string(roadmap_table, "status", "active"))
            ),
            format!(
                "status_token = {}",
                compat_toml_quote(&compat_table_string(
                    roadmap_table,
                    "status_token",
                    "ACTIVE",
                ))
            ),
            format!(
                "authoritative = {}",
                if compat_table_bool(roadmap_table, "authoritative", true) {
                    "true"
                } else {
                    "false"
                }
            ),
            format!("workstream_count = {}", rows.len()),
            format!(
                "status_allowlist = {}",
                compat_toml_string_array(&status_allowlist)
            ),
            format!(
                "priority_allowlist = {}",
                compat_toml_string_array(&priority_allowlist)
            ),
            String::new(),
            "[roadmap.schema]".to_string(),
            format!(
                "required_fields = {}",
                compat_toml_string_array(&required_fields)
            ),
            format!(
                "dependency_id_pattern = {}",
                compat_toml_quote(&compat_table_string(
                    schema_table,
                    "dependency_id_pattern",
                    "WS-*|T-*|NA-*|C-*|I-*|E-*|REQ-*",
                ))
            ),
            String::new(),
            "[roadmap.sections]".to_string(),
            format!(
                "architectural_evolution = {}",
                compat_toml_quote(&compat_table_string(
                    sections_table,
                    "architectural_evolution",
                    "## 1. Architectural Evolution",
                ))
            ),
            format!(
                "crate_ecosystem = {}",
                compat_toml_quote(&compat_table_string(
                    sections_table,
                    "crate_ecosystem",
                    "## 2. Crate Ecosystem",
                ))
            ),
            format!(
                "documentation_registry = {}",
                compat_toml_quote(&compat_table_string(
                    sections_table,
                    "documentation_registry",
                    "### 1.5 Documentation Registry Evolution (Sprint 13)",
                ))
            ),
            format!(
                "long_term_vision = {}",
                compat_toml_quote(&compat_table_string(
                    sections_table,
                    "long_term_vision",
                    "## 8. Long-Term Vision",
                ))
            ),
            format!(
                "remaining_workstreams = {}",
                compat_toml_quote(&compat_table_string(
                    sections_table,
                    "remaining_workstreams",
                    "## 7. Remaining Workstreams from ULTRA_ROADMAP.md",
                ))
            ),
            String::new(),
        ];

        for row in rows {
            lines.push("[[workstream]]".to_string());
            lines.push(format!("id = {}", compat_toml_quote(&row.id)));
            lines.push(format!("name = {}", compat_toml_quote(&row.name)));
            lines.push(format!("priority = {}", compat_toml_quote(&row.priority)));
            lines.push(format!("status = {}", compat_toml_quote(&row.status)));
            lines.push(format!(
                "status_token = {}",
                compat_toml_quote(&row.status_token)
            ));
            lines.push(format!(
                "description = {}",
                compat_toml_quote(&row.description)
            ));
            if !row.sprint.trim().is_empty() {
                lines.push(format!("sprint = {}", compat_toml_quote(&row.sprint)));
            }
            lines.push(format!(
                "primary_outputs = {}",
                compat_toml_string_array(&compat_json_string_array(&row.primary_outputs_json)?)
            ));
            let claims = compat_json_string_array(&row.claims_json)?;
            if !claims.is_empty() {
                lines.push(format!("claims = {}", compat_toml_string_array(&claims)));
            }
            if !row.insight.trim().is_empty() {
                lines.push(format!("insight = {}", compat_toml_quote(&row.insight)));
            }
            lines.push(format!(
                "dependencies = {}",
                compat_toml_string_array(&compat_json_string_array(&row.dependencies_json)?)
            ));
            lines.push(format!(
                "acceptance_criteria = {}",
                compat_toml_string_array(&compat_json_string_array(&row.acceptance_criteria_json)?)
            ));
            lines.push(format!(
                "evidence_refs = {}",
                compat_toml_string_array(&compat_json_string_array(&row.evidence_refs_json)?)
            ));
            let lacunae = compat_json_string_array(&row.lacunae_json)?;
            if !lacunae.is_empty() {
                lines.push(format!("lacunae = {}", compat_toml_string_array(&lacunae)));
            }
            lines.push(String::new());
        }

        trim_trailing_blank_lines(&mut lines);
        Ok(lines.join("\n"))
    }

    pub(crate) fn render_todo_compat_toml(&self) -> Result<String> {
        let snapshot = self.parse_registry_snapshot("todo")?;
        let todo_table = snapshot
            .as_ref()
            .and_then(|value| compat_root_table(value, "todo"));
        let schema_table = compat_child_table(todo_table, "schema");
        let rows = self.planning_todo_rows()?;
        let status_allowlist = compat_table_array(
            todo_table,
            "status_allowlist",
            &["open", "in_progress", "done", "blocked", "deferred"],
        );
        let priority_allowlist =
            compat_table_array(todo_table, "priority_allowlist", &["high", "medium", "low"]);
        let required_fields = compat_table_array(
            schema_table,
            "required_fields",
            &[
                "id",
                "area",
                "title",
                "description",
                "priority",
                "status",
                "status_token",
                "dependencies",
                "acceptance_criteria",
            ],
        );

        let mut lines = vec![
            "# GENERATED VIEW: DO NOT EDIT.".to_string(),
            "# Update via `gororoba-db planning ...` against `registry/canonical/control_plane.sqlite3`.".to_string(),
            "# To-Do Registry (SQLite compatibility export from canonical control_plane.sqlite3).".to_string(),
            "# Generated by `gororoba-db build` / `gororoba-db export-planning --table todo`.".to_string(),
            String::new(),
            "[todo]".to_string(),
            format!(
                "updated = {}",
                compat_toml_quote(&compat_table_string(todo_table, "updated", "2026-02-10"))
            ),
            format!(
                "status = {}",
                compat_toml_quote(&compat_table_string(todo_table, "status", "active"))
            ),
            format!(
                "status_token = {}",
                compat_toml_quote(&compat_table_string(todo_table, "status_token", "ACTIVE"))
            ),
            format!("item_count = {}", rows.len()),
            format!(
                "status_allowlist = {}",
                compat_toml_string_array(&status_allowlist)
            ),
            format!(
                "priority_allowlist = {}",
                compat_toml_string_array(&priority_allowlist)
            ),
            String::new(),
            "[todo.schema]".to_string(),
            format!(
                "required_fields = {}",
                compat_toml_string_array(&required_fields)
            ),
            format!(
                "dependency_id_pattern = {}",
                compat_toml_quote(&compat_table_string(
                    schema_table,
                    "dependency_id_pattern",
                    "WS-*|T-*|NA-*|C-*|I-*|E-*|REQ-*",
                ))
            ),
            String::new(),
        ];
        for row in rows {
            lines.push("[[item]]".to_string());
            lines.push(format!("id = {}", compat_toml_quote(&row.id)));
            lines.push(format!("area = {}", compat_toml_quote(&row.area)));
            lines.push(format!("title = {}", compat_toml_quote(&row.title)));
            lines.push(format!(
                "description = {}",
                compat_toml_quote(&row.description)
            ));
            lines.push(format!("priority = {}", compat_toml_quote(&row.priority)));
            lines.push(format!("status = {}", compat_toml_quote(&row.status)));
            lines.push(format!(
                "status_token = {}",
                compat_toml_quote(&row.status_token)
            ));
            lines.push(format!(
                "dependencies = {}",
                compat_toml_string_array(&compat_json_string_array(&row.dependencies_json)?)
            ));
            lines.push(format!(
                "acceptance_criteria = {}",
                compat_toml_string_array(&compat_json_string_array(&row.acceptance_criteria_json)?)
            ));
            lines.push(format!(
                "evidence_refs = {}",
                compat_toml_string_array(&compat_json_string_array(&row.evidence_refs_json)?)
            ));
            lines.push(String::new());
        }
        trim_trailing_blank_lines(&mut lines);
        Ok(lines.join("\n"))
    }

    pub(crate) fn render_next_actions_compat_toml(&self) -> Result<String> {
        let snapshot = self.parse_registry_snapshot("next_actions")?;
        let meta_table = snapshot
            .as_ref()
            .and_then(|value| compat_root_table(value, "meta"));
        let next_actions_table = snapshot
            .as_ref()
            .and_then(|value| compat_root_table(value, "next_actions"));
        let schema_table = compat_child_table(next_actions_table, "schema");
        let rows = self.planning_next_action_rows()?;
        let status_allowlist = compat_table_array(
            meta_table,
            "status_allowlist",
            &["todo", "in_progress", "done", "blocked", "deferred"],
        );
        let priority_allowlist =
            compat_table_array(meta_table, "priority_allowlist", &["high", "medium", "low"]);
        let required_fields = compat_table_array(
            schema_table,
            "required_fields",
            &[
                "id",
                "area",
                "title",
                "description",
                "priority",
                "status",
                "status_token",
                "dependencies",
                "acceptance_criteria",
            ],
        );
        let mut lines = vec![
            "# GENERATED VIEW: DO NOT EDIT.".to_string(),
            "# Update via `gororoba-db planning ...` against `registry/canonical/control_plane.sqlite3`.".to_string(),
            "# Next Actions Registry (SQLite compatibility export from canonical control_plane.sqlite3).".to_string(),
            "# Generated by `gororoba-db build` / `gororoba-db export-planning --table next-actions`.".to_string(),
            String::new(),
            "[meta]".to_string(),
            format!(
                "updated = {}",
                compat_toml_quote(&compat_table_string(meta_table, "updated", "2026-02-10"))
            ),
            format!(
                "status = {}",
                compat_toml_quote(&compat_table_string(meta_table, "status", "active"))
            ),
            format!(
                "status_token = {}",
                compat_toml_quote(&compat_table_string(meta_table, "status_token", "ACTIVE"))
            ),
            format!("action_count = {}", rows.len()),
            format!(
                "status_allowlist = {}",
                compat_toml_string_array(&status_allowlist)
            ),
            format!(
                "priority_allowlist = {}",
                compat_toml_string_array(&priority_allowlist)
            ),
            String::new(),
            "[next_actions.schema]".to_string(),
            format!(
                "required_fields = {}",
                compat_toml_string_array(&required_fields)
            ),
            format!(
                "dependency_id_pattern = {}",
                compat_toml_quote(&compat_table_string(
                    schema_table,
                    "dependency_id_pattern",
                    "WS-*|T-*|NA-*|C-*|I-*|E-*|REQ-*",
                ))
            ),
            String::new(),
        ];
        for row in rows {
            lines.push("[[action]]".to_string());
            lines.push(format!("id = {}", compat_toml_quote(&row.id)));
            lines.push(format!("area = {}", compat_toml_quote(&row.area)));
            lines.push(format!("title = {}", compat_toml_quote(&row.title)));
            lines.push(format!(
                "description = {}",
                compat_toml_quote(&row.description)
            ));
            lines.push(format!("priority = {}", compat_toml_quote(&row.priority)));
            lines.push(format!("status = {}", compat_toml_quote(&row.status)));
            lines.push(format!(
                "status_token = {}",
                compat_toml_quote(&row.status_token)
            ));
            lines.push(format!(
                "dependencies = {}",
                compat_toml_string_array(&compat_json_string_array(&row.dependencies_json)?)
            ));
            lines.push(format!(
                "acceptance_criteria = {}",
                compat_toml_string_array(&compat_json_string_array(&row.acceptance_criteria_json)?)
            ));
            lines.push(format!(
                "evidence_refs = {}",
                compat_toml_string_array(&compat_json_string_array(&row.evidence_refs_json)?)
            ));
            lines.push(String::new());
        }
        trim_trailing_blank_lines(&mut lines);
        Ok(lines.join("\n"))
    }
}
