//! Embedded Vulkan compute shader sources for TurboQuant.
//!
//! GLSL sources are compiled to SPIR-V at build time (or at runtime via
//! shaderc/glslang).  This module provides the raw GLSL source strings
//! for compilation.

/// Boundary-search quantization shader (quantize.comp).
pub const QUANTIZE_GLSL: &str = include_str!("shaders/quantize.comp");

/// Dequant + dot product shader (dequant_dot.comp).
pub const DEQUANT_DOT_GLSL: &str = include_str!("shaders/dequant_dot.comp");

/// Pre-compiled SPIR-V for quantize.comp, generated by build.rs via
/// glslc. The `.spv` file is always present (build.rs writes a 0-byte
/// placeholder when glslc is missing); the runtime VulkanQuantizer
/// inspects len() != 0 before attempting to load the module.
pub const QUANTIZE_SPV: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/turboquant_vulkan/quantize.spv"));

/// Pre-compiled SPIR-V for dequant_dot.comp.
pub const DEQUANT_DOT_SPV: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/turboquant_vulkan/dequant_dot.spv"));

/// Returns the quantize SPIR-V bytes if non-empty, else None. Use this
/// at runtime to decide between Vulkan and CPU dispatch.
pub fn quantize_spv() -> Option<&'static [u8]> {
    if QUANTIZE_SPV.is_empty() {
        None
    } else {
        Some(QUANTIZE_SPV)
    }
}

/// Returns the dequant_dot SPIR-V bytes if non-empty, else None.
pub fn dequant_dot_spv() -> Option<&'static [u8]> {
    if DEQUANT_DOT_SPV.is_empty() {
        None
    } else {
        Some(DEQUANT_DOT_SPV)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_shader_sources_embedded() {
        assert!(!QUANTIZE_GLSL.is_empty());
        assert!(QUANTIZE_GLSL.contains("TurboQuant"));
        assert!(QUANTIZE_GLSL.contains("local_size_x"));

        assert!(!DEQUANT_DOT_GLSL.is_empty());
        assert!(DEQUANT_DOT_GLSL.contains("dequant"));
        assert!(DEQUANT_DOT_GLSL.contains("local_size_x"));
    }

    #[test]
    fn test_shader_push_constants() {
        // Verify push constant blocks exist
        assert!(QUANTIZE_GLSL.contains("push_constant"));
        assert!(DEQUANT_DOT_GLSL.contains("push_constant"));
    }

    #[test]
    fn test_shader_buffer_bindings() {
        // Quantize: 3 bindings (values, boundaries, indices)
        assert!(QUANTIZE_GLSL.contains("binding = 0"));
        assert!(QUANTIZE_GLSL.contains("binding = 1"));
        assert!(QUANTIZE_GLSL.contains("binding = 2"));

        // Dequant+dot: 5 bindings (queries, indices, centroids, norms, scores)
        assert!(DEQUANT_DOT_GLSL.contains("binding = 0"));
        assert!(DEQUANT_DOT_GLSL.contains("binding = 4"));
    }
}
