//! NDJSON event reader for cross-language validation.
//!
//! WHY: The cross-language closure test requires Rust to read events produced by
//! the Haskell executable (schema/events.ndjson in the QCD repo) and reconstruct
//! T via TomographyMoments, proving that all three implementations (Haskell, Python,
//! Rust) agree on the same truth state.
//!
//! HOW: Each line is a JSON object matching schema/event.json:
//!   {"u": [ux, uy, uz], "v": [vx, vy, vz], "weight": 1.0, "dR": 0.0}
//!
//! The file is produced by: `stack exec spin-tomography-exe` in the QCD repo.

use std::{
    io::{BufRead, BufReader},
    path::Path,
};

use nalgebra::Vector3;
use serde_json::Value;

use crate::spin_event::SpinEvent;

/// Read SpinEvents from a newline-delimited JSON file.
///
/// Each line must be a JSON object with "u" (3-array), "v" (3-array).
/// "weight" is read if present (default 1.0); "dR" is ignored.
/// Returns an error if any line fails to parse.
pub fn read_events_ndjson(path: &Path) -> std::io::Result<Vec<SpinEvent>> {
    let file = std::fs::File::open(path)?;
    let reader = BufReader::new(file);

    let mut events = Vec::new();

    for (line_no, line) in reader.lines().enumerate() {
        let line = line?;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        let obj: Value = serde_json::from_str(trimmed).map_err(|e| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("line {}: JSON parse error: {e}", line_no + 1),
            )
        })?;

        let parse_vec3 = |key: &str| -> std::io::Result<Vector3<f64>> {
            let arr = obj[key].as_array().ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("line {}: missing array field '{key}'", line_no + 1),
                )
            })?;
            if arr.len() != 3 {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("line {}: field '{key}' must have 3 elements", line_no + 1),
                ));
            }
            Ok(Vector3::new(
                arr[0].as_f64().unwrap_or(0.0),
                arr[1].as_f64().unwrap_or(0.0),
                arr[2].as_f64().unwrap_or(0.0),
            ))
        };

        let u = parse_vec3("u")?;
        let v = parse_vec3("v")?;
        let weight = obj["weight"].as_f64().unwrap_or(1.0);

        // alpha1, alpha2 are not stored in the NDJSON (they are global constants).
        // We use the STAR PDG 2022 values; callers can override via SpinEvent fields.
        let mut ev = SpinEvent::new(u, v, 0.747, -0.757);
        ev.weight = weight;
        events.push(ev);
    }

    Ok(events)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event_gen::estimate_t_direct;
    use std::path::PathBuf;

    /// Path to events.ndjson produced by the Haskell executable in the QCD repo.
    /// Relative to open_gororoba workspace root (two levels up from this crate).
    fn events_path() -> PathBuf {
        // Locate the file relative to the workspace Cargo.toml.
        // open_gororoba lives at ~/Github/open_gororoba/
        // QCD lives at ~/Playground/QCD/
        // schema/events.ndjson is at ~/Playground/QCD/schema/events.ndjson
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../Playground/QCD/schema/events.ndjson")
    }

    #[test]
    fn test_cross_language_closure_rust_reads_haskell_events() {
        // WHY: Proves the three-way closure: Haskell generates -> Python reads (done),
        // Rust reads (this test) -> all recover P = 1/3 from the same event file.
        let path = events_path();
        if !path.exists() {
            // Skip gracefully -- file is generated by `stack exec spin-tomography-exe`
            // in the QCD repo. Not present in a clean open_gororoba checkout.
            eprintln!(
                "SKIP test_cross_language_closure: {} not found. \
                 Run `stack exec spin-tomography-exe` in ~/Playground/QCD first.",
                path.display()
            );
            return;
        }

        let events = read_events_ndjson(&path).expect("Failed to read events.ndjson");
        assert!(!events.is_empty(), "events.ndjson must be non-empty");

        // Use estimate_t_direct: matches Python/Haskell centered moment estimator.
        // alpha1/alpha2 are stored on each SpinEvent (set by read_events_ndjson).
        let alpha1 = 0.747_f64;
        let alpha2 = -0.757_f64;
        let (_a, _b, t_rec) = estimate_t_direct(&events, alpha1, alpha2);
        let p_rec = t_rec.trace() / 3.0;
        let p_truth = 1.0_f64 / 3.0;
        let tol = 0.05_f64;

        assert!(
            (p_rec - p_truth).abs() < tol,
            "Cross-language closure (Rust reads Haskell events): \
             P_rec={p_rec:.4}, P_truth={p_truth:.4}, diff={:.4} >= tol={tol}",
            (p_rec - p_truth).abs()
        );
    }

    #[test]
    fn test_read_events_ndjson_from_tempfile() {
        // Unit test that does not require the QCD repo to be present.
        use std::io::Write;
        let mut tmp = tempfile::NamedTempFile::new().unwrap();
        writeln!(
            tmp,
            r#"{{"u":[1.0,0.0,0.0],"v":[0.0,1.0,0.0],"weight":1.0,"dR":0.0}}"#
        )
        .unwrap();
        writeln!(
            tmp,
            r#"{{"u":[0.0,0.0,1.0],"v":[1.0,0.0,0.0],"weight":2.0,"dR":0.0}}"#
        )
        .unwrap();

        let events = read_events_ndjson(tmp.path()).unwrap();
        assert_eq!(events.len(), 2);
        assert!((events[0].n1[0] - 1.0).abs() < 1e-14);
        assert!((events[1].weight - 2.0).abs() < 1e-14);
    }
}
