//! Heliosphere analysis lanes, each exposing a `Cli` argument struct and a `run`
//! entry point behind the `heliosphere` subcommand dispatcher.

pub mod algebra_decompose;
pub mod associator_null_audit;
pub mod baseline_comparison;
pub mod beta_join;
pub mod bootstrap_f1;
pub mod boundary_survey;
#[cfg(feature = "gpu")]
pub mod boxkite_alignment;
pub mod boxkite_parity;
pub mod commutator_baseline;
pub mod cross_mission_invariance;
pub mod decomposition_audit;
pub mod effective_rank;
pub mod embed_pca;
pub mod fa_attribution;
pub mod fa_cross_mission_table;
pub mod falsification_audit;
pub mod feature_cube;
pub mod feature_transform;
pub mod fte_case_study;
pub mod full_sweep;
pub mod hybrid_detector;
pub mod l2_delay_baseline;
pub mod lag_depth_sweep;
#[cfg(feature = "gpu")]
pub mod lbm_cube_run;
pub mod magnetic_takens;
pub mod maven_crossing_gen;
pub mod mms_multiday;
pub mod mms_sitl_labeled;
pub mod norm_dump;
pub mod order_surplus;
pub mod pca_variance_baseline;
pub mod predictive_eval;
pub mod psp_alfven_control;
pub mod psp_encounter_summary;
pub mod psp_switchback_correlation;
pub mod q2_transverse;
pub mod quench_scan;
pub mod r16_ablation;
pub mod r64_ablation;
pub mod random_trilinear;
pub mod random_trilinear_sparse;
pub mod rosetta_ablation_summary;
pub mod rosetta_draping;
pub mod selfsim_logstats;
pub mod sparse_policy_mainline;
#[cfg(feature = "gpu")]
pub mod sparse_preservation;
pub mod switchback_omega;
pub mod synthetic_mhd;
pub mod takens_tau_sweep;
pub mod temporal_overlay;
pub mod themis_general_benchmark;
pub mod themis_staples_labeled;
pub mod voyager_heliopause;
pub mod window_sensitivity;
pub mod zd_audit;
