[package]
name = "lbm_vulkan"
version = "0.1.0"
edition = { workspace = true }
license = "GPL-2.0-only"
repository = "https://github.com/Oichkatzelesfrettschen/open_gororoba"

[dependencies]
ash = { workspace = true, features = ["debug", "libloading", "loaded"] }
gpu-allocator = { workspace = true, features = ["vulkan"] }
half = { workspace = true }
gororoba_gpu_readback = { workspace = true }
log = { workspace = true }
image = { workspace = true }
naga = { workspace = true, features = ["wgsl-in", "spv-out"] }
env_logger = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
winit = { workspace = true }
raw-window-handle = { workspace = true }

[lints]
workspace = true
