[package]
name = "cd_spin_bridge"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
spin_tomography_core = { path = "../spin_tomography_core" }
sign_imbalance = { path = "../sign_imbalance" }
algebra_core = { path = "../algebra_core" }
nalgebra = { workspace = true }
num-complex = { workspace = true }

[lints]
workspace = true
