#!/usr/bin/env python3
"""
Bootstrap reports/*.md into a TOML-first registry.

Input:
- reports/*.md

Output:
- registry/reports_narratives.toml
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

CLAIM_RE = re.compile(r"\bC-\d{3}\b")
BACKTICK_RE = re.compile(r"`([^`\n]+)`")
HEADING_RE = re.compile(r"^#\s+(.+?)\s*$", flags=re.M)


@dataclass(frozen=True)
class ReportDoc:
    doc_id: str
    source_markdown: str
    slug: str
    title: str
    category: str
    claim_refs: list[str]
    path_refs: list[str]
    line_count: int
    body_markdown: str


def _assert_ascii(text: str, context: str) -> None:
    bad = sorted({ch for ch in text if ord(ch) > 127})
    if bad:
        sample = "".join(bad[:20])
        raise SystemExit(f"ERROR: Non-ASCII output in {context}: {sample!r}")


def _ascii_sanitize(text: str) -> str:
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2026": "...",
        "\u00a0": " ",
    }
    out: list[str] = []
    for ch in text:
        mapped = replacements.get(ch, ch)
        for item in mapped:
            code = ord(item)
            if item in {"\n", "\r", "\t"}:
                out.append(item)
            elif code < 32:
                out.append(" ")
            elif code <= 127:
                out.append(item)
            else:
                out.append(f"<U+{code:04X}>")
    return "".join(out)


def _escape(text: str) -> str:
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _render_list(values: list[str]) -> str:
    if not values:
        return "[]"
    return "[" + ", ".join(_escape(v) for v in values) + "]"


def _render_multiline(text: str) -> str:
    if "'''" not in text:
        return "'''\n" + text + "\n'''"
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _title(text: str, fallback: str) -> str:
    match = HEADING_RE.search(text)
    return match.group(1).strip() if match else fallback


def _paths(text: str) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for raw in BACKTICK_RE.findall(text):
        token = raw.strip()
        if not token:
            continue
        if token.startswith("http://") or token.startswith("https://"):
            continue
        if "/" not in token and "." not in token:
            continue
        if token in seen:
            continue
        seen.add(token)
        out.append(token)
    return out


def _category(filename: str) -> str:
    name = filename.lower()
    if name.startswith("claims_batch_backlog_"):
        return "claims_backlog"
    if "audit" in name:
        return "audit"
    if "inventory" in name:
        return "inventory"
    if "plan" in name:
        return "plan"
    if "status" in name:
        return "status"
    return "report"


def _parse_doc(index: int, rel: Path, text: str) -> ReportDoc:
    sanitized = _ascii_sanitize(text)
    return ReportDoc(
        doc_id=f"RPT-{index:03d}",
        source_markdown=rel.as_posix(),
        slug=rel.stem,
        title=_title(sanitized, rel.stem),
        category=_category(rel.name),
        claim_refs=sorted(set(CLAIM_RE.findall(sanitized))),
        path_refs=_paths(sanitized),
        line_count=len(sanitized.splitlines()),
        body_markdown=sanitized.rstrip("\n"),
    )


def _render_toml(records: list[ReportDoc]) -> str:
    lines: list[str] = []
    lines.append("# Reports narratives registry (TOML-first).")
    lines.append("# Generated by src/scripts/analysis/normalize_reports_narratives_registry.py")
    lines.append("")
    lines.append("[reports_narratives]")
    lines.append('updated = "2026-02-09"')
    lines.append("authoritative = true")
    lines.append('source_markdown_glob = "reports/*.md"')
    lines.append(f"document_count = {len(records)}")
    lines.append("")
    for rec in records:
        lines.append("[[document]]")
        lines.append(f"id = {_escape(rec.doc_id)}")
        lines.append(f"source_markdown = {_escape(rec.source_markdown)}")
        lines.append(f"slug = {_escape(rec.slug)}")
        lines.append(f"title = {_escape(rec.title)}")
        lines.append(f"category = {_escape(rec.category)}")
        lines.append(f"claim_refs = {_render_list(rec.claim_refs)}")
        lines.append(f"path_refs = {_render_list(rec.path_refs)}")
        lines.append(f"line_count = {rec.line_count}")
        lines.append(f"body_markdown = {_render_multiline(rec.body_markdown)}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        default=str(Path(__file__).resolve().parents[3]),
        help="Repository root.",
    )
    parser.add_argument(
        "--bootstrap-from-markdown",
        action="store_true",
        help="Required flag to ingest markdown into TOML registry.",
    )
    parser.add_argument(
        "--out",
        default="registry/reports_narratives.toml",
        help="Output TOML registry path.",
    )
    args = parser.parse_args()

    if not args.bootstrap_from_markdown:
        raise SystemExit("ERROR: pass --bootstrap-from-markdown to ingest markdown sources")

    root = Path(args.repo_root).resolve()
    files = sorted((root / "reports").glob("*.md"))
    if not files:
        raise SystemExit("ERROR: no reports markdown files found")

    records: list[ReportDoc] = []
    for idx, path in enumerate(files, start=1):
        records.append(_parse_doc(idx, path.relative_to(root), path.read_text(encoding="utf-8", errors="ignore")))

    out_text = _render_toml(records)
    out_path = root / args.out
    _assert_ascii(out_text, str(out_path))
    out_path.write_text(out_text, encoding="utf-8")
    print(f"Wrote {out_path} with {len(records)} documents.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
