[package]
name = "grmhd_core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
rayon = { workspace = true }
wide = { workspace = true }
cudarc = { workspace = true, optional = true }

[features]
default = []
gpu = ["dep:cudarc"]

[lints]
workspace = true
