#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date +%Y%m%d%H%M%S)"
FORCE=0
WRITE_GEMINI=0
XDG_CONFIG_HOME_DEFAULT="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME_DEFAULT="${XDG_CACHE_HOME:-$HOME/.cache}"
NEXTTEST_CONFIG_PATH="$XDG_CONFIG_HOME_DEFAULT/nextest.toml"
GOROROBA_LIT_CACHE_PATH="$XDG_CACHE_HOME_DEFAULT/gororoba-lit-cache"
CARGO_BUILD_DIR_SELECTED=""
CARGO_BUILD_DIR_REASON=""

usage() {
  cat <<'EOF'
Usage: scripts/bootstrap_user_local_xdg.sh [--force] [--with-gemini]

Install open_gororoba developer config into user-local locations only:

- ~/.cargo/config.toml
- $XDG_CONFIG_HOME/nextest.toml (defaults to ~/.config/nextest.toml)
- $XDG_CACHE_HOME/gororoba-lit-cache/ (defaults to ~/.cache/gororoba-lit-cache/)
- ~/.gemini/settings.json (optional; only with --with-gemini)

Existing files are backed up with a timestamp suffix unless --force is used.

Credential-bearing runtime variables are documented in:
- docs/engineering/runtime_env_inventory.txt
- docs/engineering/lit_search_env_vars.txt
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --with-gemini)
      WRITE_GEMINI=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

backup_if_needed() {
  local path="$1"
  if [[ -e "$path" && "$FORCE" != "1" ]]; then
    cp "$path" "${path}.bak.${STAMP}"
  fi
}

require_writable_dir() {
  local path="$1"
  if [[ ! -d "$path" ]]; then
    echo "ERROR: expected directory does not exist: $path" >&2
    exit 1
  fi
  if [[ ! -w "$path" ]]; then
    echo "ERROR: directory is not writable: $path" >&2
    exit 1
  fi
}

select_cargo_build_dir() {
  local -a candidate_roots=()
  local -a candidate_reasons=()
  local -a fallback_details=()
  local candidate_root=""
  local candidate_dir=""
  local idx=0

  if [[ -n "${TMPDIR:-}" ]]; then
    candidate_roots+=("$TMPDIR")
    candidate_reasons+=("TMPDIR is set and writable")
  else
    fallback_details+=("TMPDIR is unset")
  fi

  candidate_roots+=("/srv/fast/tmp")
  candidate_reasons+=("/srv/fast/tmp is writable")
  candidate_roots+=("$XDG_CACHE_HOME_DEFAULT")
  candidate_reasons+=("using XDG cache fallback")

  for idx in "${!candidate_roots[@]}"; do
    candidate_root="${candidate_roots[$idx]}"
    candidate_dir="$candidate_root/open_gororoba-cargo-build/ambient"
    if mkdir -p "$candidate_dir" 2>/dev/null && [[ -w "$candidate_dir" ]]; then
      CARGO_BUILD_DIR_SELECTED="$candidate_dir"
      CARGO_BUILD_DIR_REASON="${candidate_reasons[$idx]}"
      break
    fi
    fallback_details+=("skipped '$candidate_root' (unable to create/write '$candidate_dir')")
  done

  if [[ -z "$CARGO_BUILD_DIR_SELECTED" ]]; then
    echo "ERROR: unable to select a writable Cargo build-dir root." >&2
    for detail in "${fallback_details[@]}"; do
      echo "  - $detail" >&2
    done
    exit 1
  fi

  echo "Selected Cargo build-dir: $CARGO_BUILD_DIR_SELECTED"
  echo "  reason: $CARGO_BUILD_DIR_REASON"
  if [[ "${#fallback_details[@]}" -gt 0 ]]; then
    echo "  fallback details:"
    for detail in "${fallback_details[@]}"; do
      echo "    - $detail"
    done
  fi
}

select_cargo_build_dir

mkdir -p "$HOME/.cargo" "$XDG_CONFIG_HOME_DEFAULT" "$GOROROBA_LIT_CACHE_PATH" "$CARGO_BUILD_DIR_SELECTED"
require_writable_dir "$HOME/.cargo"
require_writable_dir "$XDG_CONFIG_HOME_DEFAULT"
require_writable_dir "$GOROROBA_LIT_CACHE_PATH"
require_writable_dir "$CARGO_BUILD_DIR_SELECTED"

backup_if_needed "$HOME/.cargo/config.toml"
cat >"$HOME/.cargo/config.toml" <<EOF
# open_gororoba user-local Cargo configuration
# Generated by $ROOT/scripts/bootstrap_user_local_xdg.sh on $STAMP

[build]
target-dir = "$ROOT/.cache/cargo-default-target"
build-dir = "$CARGO_BUILD_DIR_SELECTED"
incremental = false

[env]
CARGO_INCREMENTAL = "0"

[cache]
auto-clean-frequency = "1 day"

[unstable]
gc = true

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=mold", "-Dwarnings"]
linker = "clang"

[profile.dev]
split-debuginfo = "unpacked"
EOF

backup_if_needed "$NEXTTEST_CONFIG_PATH"
cat >"$NEXTTEST_CONFIG_PATH" <<'EOF'
[profile.default]
failure-output = "final"
fail-fast = false
status-level = "slow"
final-status-level = "slow"
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
failure-output = "immediate-final"
fail-fast = false
status-level = "slow"
final-status-level = "all"
slow-timeout = { period = "90s", terminate-after = 2 }

[profile.smoke]
failure-output = "immediate-final"
fail-fast = true
status-level = "all"
final-status-level = "all"

[profile.heavy]
failure-output = "immediate-final"
fail-fast = false
status-level = "slow"
final-status-level = "all"
slow-timeout = { period = "180s", terminate-after = 2 }

[test-groups]
heavy-math = { max-threads = 1 }
heavy-research = { max-threads = 1 }
serial-gpu = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(algebra_analysis) or package(gr_core)'
test-group = "heavy-math"
slow-timeout = { period = "180s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'package(algebra_analysis) or package(gr_core)'
test-group = "heavy-math"
slow-timeout = { period = "240s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'package(algebra_analysis) or package(gr_core)'
test-group = "heavy-math"
slow-timeout = { period = "600s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'package(stats_core) and test(/ultrametric::baire_codebook::tests::(test_euclidean_ultrametricity_across_filtration_levels|test_intermediate_filtration_gradient|test_random_removal_control|test_lambda512_to_256_intermediate_gradient|test_lambda512_to_256_random_removal_control|test_sbase_to_lambda2048_gradient|test_l0_subpopulation_ultrametricity|test_lambda2048_to_1024_intermediate_gradient|test_l1_filter_on_l0_neg1_subset|test_recursive_simpsons_paradox_l2|test_cross_stratum_triple_decomposition|test_l0_zero_simpsons_paradox|test_dimensional_universality_simpsons_paradox|test_lambda1024_stratum_paradox_and_summary)/)'
test-group = "heavy-research"
slow-timeout = { period = "600s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'package(algebra_experimental) and test(test_thesis_e_xor_involution_invariants_128d)'
test-group = "heavy-research"
slow-timeout = { period = "600s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'package(gororoba_algebra) and test(test_split_octonion_attractor_regression_dim_128_256_guarded)'
test-group = "heavy-research"
slow-timeout = { period = "600s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'package(gororoba_cli) and test(test_zero_divisor_scaling)'
test-group = "heavy-research"
slow-timeout = { period = "600s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'package(sign_imbalance) and test(test_kubo_j1j2_alpha_sweep)'
test-group = "heavy-research"
slow-timeout = { period = "600s", terminate-after = 2 }

[[profile.heavy.overrides]]
filter = 'test(/gpu/)'
test-group = "serial-gpu"
EOF

if [[ "$WRITE_GEMINI" == "1" ]]; then
  mkdir -p "$HOME/.gemini"
  backup_if_needed "$HOME/.gemini/settings.json"
  cat >"$HOME/.gemini/settings.json" <<'EOF'
{
  "context": {
    "discoveryMaxDirs": 100
  },
  "fileReadLineLimit": 500
}
EOF
fi

echo "Installed user-local open_gororoba config:"
echo "  ~/.cargo/config.toml"
echo "  $NEXTTEST_CONFIG_PATH"
echo "  $GOROROBA_LIT_CACHE_PATH/"
if [[ "$WRITE_GEMINI" == "1" ]]; then
  echo "  ~/.gemini/settings.json"
fi
echo
echo "User-local runtime variable guidance:"
echo "  $ROOT/docs/engineering/runtime_env_inventory.txt"
echo "  $ROOT/docs/engineering/lit_search_env_vars.txt"
