import os


def assemble_manuscript():
    print("--- ASSEMBLING FINAL MANUSCRIPT ---")

    # 1. Manifest
    files_to_merge = [
        'docs/UNIFIED_WHITEPAPER.md',
        'docs/THEORETICAL_SYNTHESIS_V2.md',
        'docs/SEDENION_GRAVASTAR_EQUIVALENCE.md',
        'docs/PHYSICAL_INTERPRETATION.md',
        'docs/UNIFIED_FRAMEWORK_V2.md',
        'docs/x86_SIMD_OPTIMIZATION.md',
        'docs/RESEARCH_STATUS_HYPER.md'
    ]

    final_content = "# THE GRAND UNIFICATION: SEDENION-GRAVASTAR FIELD THEORY\n\n"
    final_content += "**Generated by Gemini CLI | Date: January 26, 2026**\n\n"
    final_content += "---\n\n"

    # 2. Merge Content
    for fpath in files_to_merge:
        if os.path.exists(fpath):
            print(f"Merging {fpath}...")
            with open(fpath, 'r') as f:
                content = f.read()
                # Demote headers to nest them
                content = content.replace("# ", "## ")
                final_content += f"\n\n# SECTION: {os.path.basename(fpath)}\n\n"
                final_content += content
        else:
            print(f"Warning: {fpath} missing.")

    # 3. Add Visual Gallery
    final_content += "\n\n# SECTION: VISUAL GALLERY (HYPER-STANDARD)\n\n"
    final_content += "The following artifacts represent the visualization of the theory at 3160x2820 resolution.\n\n"

    images = [
        "data/artifacts/images/hyper_fractal_sedenion.png",
        "data/artifacts/images/hyper_mass_ladder_v2.png",
        "data/artifacts/images/hyper_mera_network_v2.png",
        "data/artifacts/images/genesis_simulation_grand.png",
        "data/artifacts/images/genesis_trajectory_viz.png"
    ]

    for img in images:
        final_content += f"### {os.path.basename(img)}\n![Artifact]({img})\n\n"

    # 4. Save
    with open('docs/FINAL_MANUSCRIPT.md', 'w') as f:
        f.write(final_content)

    print("Manuscript assembled at docs/FINAL_MANUSCRIPT.md")

if __name__ == "__main__":
    assemble_manuscript()
