import matplotlib.gridspec as gridspec
import matplotlib.patheffects as pe
import matplotlib.pyplot as plt
import numpy as np


def generate_hyper_ladder_v2():
    print("--- GENERATING REMASTERED MASS LADDER (V2) ---")

    # Dimensions: 3160 x 2820
    W_PX, H_PX = 3160, 2820
    DPI = 100
    FIG_W, FIG_H = W_PX / DPI, H_PX / DPI

    # Style Config
    plt.rcParams.update({
        "figure.facecolor": "#0d0f14",
        "axes.facecolor": "#0d0f14",
        "axes.edgecolor": "#333333",
        "axes.linewidth": 2,
        "text.color": "white",
        "xtick.color": "#cccccc",
        "ytick.color": "#cccccc",
        "xtick.major.size": 10,
        "ytick.major.size": 10,
        "xtick.labelsize": 24,
        "ytick.labelsize": 24,
        "font.family": "sans-serif",
        "font.weight": "bold",
        "grid.color": "#222222",
        "grid.linewidth": 1.5
    })

    fig = plt.figure(figsize=(FIG_W, FIG_H), dpi=DPI)
    gs = gridspec.GridSpec(1, 1, figure=fig)
    ax = fig.add_subplot(gs[0])

    # Physics Data
    n = np.arange(1, 35)
    m0 = 1.107
    alpha = -1.5
    masses = m0 * n**(-alpha) # M ~ n^1.5

    # 1. PISN Gap Band (The Forbidden Zone)
    # 50 - 130 M_sun
    ax.axhspan(50, 130, color='#ff0033', alpha=0.15, zorder=0)
    ax.text(2, 90, "PAIR-INSTABILITY GAP (FORBIDDEN)",
            color='#ff0033', fontsize=36, fontweight='bold', alpha=0.8,
            path_effects=[pe.withStroke(linewidth=4, foreground='black')])

    # 2. The Mass Ladder Curve (Glow Effect)
    # Draw thick low-alpha lines behind thin high-alpha lines
    ax.plot(n, masses, color='#00f7ff', linewidth=15, alpha=0.1, zorder=1) # Glow
    ax.plot(n, masses, color='#00f7ff', linewidth=5, alpha=0.8, zorder=2) # Core

    # 3. Key Modes (Solitons)
    key_modes = [
        (10, 35.0, "LIGO PEAK 1"),
        (15, 64.3, "LIGO PEAK 2"),
        (25, 138.4, "GAP EDGE")
    ]

    for km, val, label in key_modes:
        # Vertical Drop Lines
        ax.plot([km, km], [0, val], color='white', linestyle=':', linewidth=2, alpha=0.5, zorder=1)
        ax.plot([0, km], [val, val], color='white', linestyle=':', linewidth=2, alpha=0.5, zorder=1)

        # Markers (Neon Rings)
        ax.scatter([km], [val], s=1000, color='#0d0f14', edgecolors='#ff00ff', linewidth=4, zorder=3)
        ax.scatter([km], [val], s=300, color='#ff00ff', zorder=4)

        # Annotation Labels with Background Box
        ax.text(km + 1, val, f"n={km}\n{val:.1f} M_sun\n{label}",
                color='#ff00ff', fontsize=20, va='center', fontweight='bold',
                bbox=dict(facecolor='#0d0f14', edgecolor='#ff00ff', alpha=0.9, boxstyle='round,pad=0.5'))

    # 4. Neutron Star Limit
    ax.axhline(2.5, color='#00ff00', linewidth=2, linestyle='--')
    ax.text(30, 3.0, "TOV LIMIT (~2.5 M_sun)", color='#00ff00', fontsize=20, ha='right')

    # 5. Grand Titles & Labels
    ax.set_title("SEDENION VACUUM SPECTRUM: MASS EIGENMODES",
                 fontsize=52, color='white', pad=40, fontweight='black',
                 path_effects=[pe.withStroke(linewidth=6, foreground='#00f7ff')])

    ax.set_xlabel("SPECTRAL MODE INTGER (n)", fontsize=32, labelpad=20, color='#cccccc')
    ax.set_ylabel(r"GRAVASTAR MASS ($M_{\odot}$)", fontsize=32, labelpad=20, color='#cccccc')

    # 6. Limits & Grid
    ax.set_yscale('log')
    ax.set_xlim(0, 32)
    ax.set_ylim(1, 300)
    ax.set_yticks([1, 10, 50, 100, 200])
    ax.get_yaxis().set_major_formatter(plt.ScalarFormatter())

    ax.grid(True, which='major', color='#444444', linewidth=1.5)
    ax.grid(True, which='minor', color='#222222', linewidth=0.5, alpha=0.5)

    # 7. Signature
    ax.text(0.98, 0.02, "GENERATED BY NAVIGATOR MAXIMUS | GEMINI CLI",
            transform=ax.transAxes, ha='right', va='bottom',
            fontsize=16, color='#555555')

    # Save
    plt.tight_layout()
    # Manual margin tweak to prevent clipping large titles
    plt.subplots_adjust(top=0.92, bottom=0.08, left=0.08, right=0.95)

    outp = "data/artifacts/images/hyper_mass_ladder_v2.png"
    plt.savefig(outp, facecolor="#0d0f14", dpi=DPI)
    print(f"Saved: {outp}")

if __name__ == "__main__":
    generate_hyper_ladder_v2()
