import matplotlib.patheffects as pe
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np


def generate_hyper_mera_v2():
    print("--- GENERATING REMASTERED MERA NETWORK (V2) ---")

    W_PX, H_PX = 3160, 2820
    DPI = 100
    FIG_W, FIG_H = W_PX / DPI, H_PX / DPI

    plt.rcParams.update({
        "figure.facecolor": "#0d0f14",
        "axes.facecolor": "#0d0f14",
        "text.color": "white",
        "font.family": "sans-serif",
    })

    fig, ax = plt.subplots(figsize=(FIG_W, FIG_H), dpi=DPI)
    ax.set_facecolor("#0d0f14")

    # 1. Geometry Setup (Radial)
    depth = 6
    leaves = 2**depth # 64 boundary nodes
    G = nx.Graph()
    pos = {}

    # Rings radii
    radii = np.linspace(10, 2, depth+1)

    # 2. Build Tree
    layer_nodes = []

    # Boundary Layer (0)
    for i in range(leaves):
        theta = 2 * np.pi * i / leaves
        nid = f"0_{i}"
        G.add_node(nid, layer=0, type='phys')
        pos[nid] = (radii[0] * np.cos(theta), radii[0] * np.sin(theta))
        layer_nodes.append(nid)

    # Bulk Layers
    for d in range(1, depth+1):
        prev_nodes = layer_nodes
        layer_nodes = []
        count = len(prev_nodes) // 2

        for i in range(count):
            nid = f"{d}_{i}"
            # Position is average of children angles
            child1 = prev_nodes[2*i]
            child2 = prev_nodes[2*i+1]
            p1 = np.array(pos[child1])
            p2 = np.array(pos[child2])
            pmid = (p1 + p2) / 2
            # Project to correct radius
            norm = np.linalg.norm(pmid)
            if norm == 0: norm = 1
            pos[nid] = pmid / norm * radii[d]

            G.add_node(nid, layer=d, type='renorm')
            G.add_edge(child1, nid, type='tree')
            G.add_edge(child2, nid, type='tree')

            layer_nodes.append(nid)

    # 3. Add Sedenion Wormholes (Non-Local)
    import random
    random.seed(137)
    boundary_nodes = [n for n,d in G.nodes(data=True) if d['layer']==0]

    for _ in range(25):
        u, v = random.sample(boundary_nodes, 2)
        # Only add if geometrically distant
        dist = np.linalg.norm(np.array(pos[u]) - np.array(pos[v]))
        if dist > 15.0: # Across the void
            G.add_edge(u, v, type='wormhole')

    # 4. Drawing (Layered for Glow)

    # A. Wormholes (Deep Layer) - Magenta Neon
    wh_edges = [e for e in G.edges() if G.edges[e].get('type') == 'wormhole']
    # Glow
    nx.draw_networkx_edges(G, pos, edgelist=wh_edges, edge_color='#ff00ff',
                           width=6, alpha=0.1, ax=ax)
    nx.draw_networkx_edges(G, pos, edgelist=wh_edges, edge_color='#ff00ff',
                           width=2, alpha=0.8, style='dashed', ax=ax)

    # B. Tree Structure (Cyan Neon)
    tree_edges = [e for e in G.edges() if G.edges[e].get('type') == 'tree']
    nx.draw_networkx_edges(G, pos, edgelist=tree_edges, edge_color='#00ffff',
                           width=4, alpha=0.1, ax=ax) # Glow
    nx.draw_networkx_edges(G, pos, edgelist=tree_edges, edge_color='#00ffff',
                           width=1, alpha=0.6, ax=ax) # Core

    # C. Nodes (White Stars)
    phys_nodes = [n for n,d in G.nodes(data=True) if d['type']=='phys']
    bulk_nodes = [n for n,d in G.nodes(data=True) if d['type']=='renorm']

    # Boundary
    nx.draw_networkx_nodes(G, pos, nodelist=phys_nodes, node_color='white',
                           node_size=80, alpha=1.0, ax=ax)
    # Bulk
    nx.draw_networkx_nodes(G, pos, nodelist=bulk_nodes, node_color='#00ffff',
                           node_size=40, alpha=0.8, ax=ax)

    # 5. Grand Typography
    ax.set_title("HOLOGRAPHIC TENSOR NETWORK\nSEDENION BULK GEOMETRY",
                 fontsize=50, fontweight='bold', color='white', pad=40)

    # Annotations
    ax.text(0, -13, "BOUNDARY CFT (1D)", fontsize=30, color='white',
            ha='center', fontweight='bold',
            path_effects=[pe.withStroke(linewidth=4, foreground='black')])

    ax.text(0, 0, "AdS BULK\n(D = -1.5)", fontsize=24, color='#00ffff',
            ha='center', va='center', fontweight='bold',
            bbox=dict(facecolor='#0d0f14', edgecolor='#00ffff', alpha=0.8))

    ax.text(12, 12, "WORMHOLE\n(Non-Associative)", fontsize=20, color='#ff00ff',
            ha='right', va='top')

    ax.axis('off')
    ax.set_xlim(-14, 14)
    ax.set_ylim(-14, 14)

    # Signature
    ax.text(0.95, 0.02, "GENERATED BY NAVIGATOR MAXIMUS",
            transform=ax.transAxes, ha='right', fontsize=18, color='#555555')

    plt.tight_layout()
    outp = "data/artifacts/images/hyper_mera_network_v2.png"
    plt.savefig(outp, facecolor="#0d0f14", dpi=DPI)
    print(f"Saved: {outp}")

if __name__ == "__main__":
    generate_hyper_mera_v2()
