import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap


def generate_hyper_fractal_vis():
    print("--- Generating Hyper-Fractal Sedenion Visualization (3160x2820) ---")

    # Parameters for high-res output
    W, H = 3160, 2820
    DPI = 300

    # Create fractal lattice
    # We simulate the "Box-Kite" projection into 2D complex plane
    # utilizing a domain coloring approach for the Sedenion Zero-Divisor function

    x = np.linspace(-2, 2, 1000)
    y = np.linspace(-2, 2, 1000)
    X, Y = np.meshgrid(x, y)
    Z = X + 1j * Y

    # The "Fractal Potential" V(z) ~ sum z^(-n)
    # Simulating the Negative Dimension series
    V = np.zeros_like(Z, dtype=np.complex128)
    for n in range(1, 8):
        # We add terms with alternating phases to simulate non-associativity noise
        phase = np.exp(1j * n * np.pi / 4)
        V += phase / (Z**n + 0.1) # Softened singularity

    # Magnitude and Phase for coloring
    Mag = np.abs(V)
    Phase = np.angle(V)

    # Custom Dark Mode Colormap (Neon/Cyberpunk)
    colors = [(0, 0, 0), (0.2, 0, 0.4), (0, 0.5, 1), (0, 1, 0.5), (1, 1, 1)]
    cmap = LinearSegmentedColormap.from_list("SedenionNeon", colors, N=256)

    # Plotting
    fig = plt.figure(figsize=(W/DPI, H/DPI), dpi=DPI, facecolor='#0d0f14')
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis('off')

    # Log scaling for magnitude to see structure
    img = ax.imshow(np.log(Mag + 1e-9), cmap=cmap, extent=[-2, 2, -2, 2], origin='lower')

    # Overlay Phase Contours
    ax.contour(X, Y, Phase, levels=20, colors='white', linewidths=0.3, alpha=0.3)

    # Annotations
    ax.text(-1.8, 1.8, "SEDENION ZERO-DIVISOR FIELD", color='white', fontsize=24, fontweight='bold')
    ax.text(-1.8, 1.7, "Projected onto Complex Plane (D -> -Infinity)", color='cyan', fontsize=16)
    ax.text(1.2, -1.8, "Generated by Gemini CLI", color='gray', fontsize=12)

    output_path = "data/artifacts/images/hyper_fractal_sedenion.png"
    plt.savefig(output_path, facecolor='#0d0f14', dpi=DPI)
    print(f"Saved Hyper-Fractal Visualization to {output_path}")

if __name__ == "__main__":
    generate_hyper_fractal_vis()
