// build.rs -- materials_data codegen
//
// WHY: Storing 17K+ lines of float literals as Rust source inflates rustc's
//      parse + type-check work on every incremental build and makes CPD scans
//      quadratically expensive. This script reads human-readable CSV data from
//      data/nk/ and emits the matching const arrays into OUT_DIR.
//
// Output files:
//   $OUT_DIR/generated_nk_tables.rs   -- all tabulated n,k const arrays
//   $OUT_DIR/generated_optical_params.rs -- placeholder (Phase 3 / task #57)
//   $OUT_DIR/generated_crystal_tables.rs -- placeholder (Phase 4 / task #58)

use std::env;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, Write};
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let data_nk = manifest.join("data").join("nk");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data/");

    // ---------- Phase 2: tabulated n,k tables ----------
    let nk_out = out_dir.join("generated_nk_tables.rs");
    let mut nk_file = File::create(&nk_out).expect("failed to create generated_nk_tables.rs");

    writeln!(
        nk_file,
        "// Auto-generated by materials_data/build.rs -- do not edit.\n\
         // Source: crates/materials_data/data/nk/*.csv\n"
    )
    .unwrap();

    // Map from CSV file stem to the const name prefix used in materials_core.
    let nk_sources: &[(&str, &str)] = &[
        ("au_jc1972",           "JC_AU"),
        ("ag_jc1972",           "JC_AG"),
        ("cu_jc1972",           "JC_CU"),
        ("au_ordal_jc",         "SPLICED_AU"),
        ("cu_ordal_jc",         "SPLICED_CU"),
        ("au_ordal_jc_henke",   "SPLICED3_AU"),
        ("ag_ordal_jc_henke",   "SPLICED3_AG"),
        ("cu_ordal_jc_henke",   "SPLICED3_CU"),
    ];

    for (stem, prefix) in nk_sources {
        let csv_path = data_nk.join(format!("{stem}.csv"));
        println!("cargo:rerun-if-changed=data/nk/{stem}.csv");

        let rows = read_nk_csv(&csv_path);
        let n = rows.len();

        emit_f64_const(&mut nk_file, &format!("{prefix}_EV"), n, rows.iter().map(|r| r.0));
        emit_f64_const(&mut nk_file, &format!("{prefix}_N"),  n, rows.iter().map(|r| r.1));
        emit_f64_const(&mut nk_file, &format!("{prefix}_K"),  n, rows.iter().map(|r| r.2));
    }

    // ---------- Placeholders for future phases ----------
    let optical_out = out_dir.join("generated_optical_params.rs");
    if !optical_out.exists() {
        fs::write(
            &optical_out,
            "// generated_optical_params.rs -- placeholder (Phase 3 / task #57 pending)\n",
        )
        .expect("failed to write generated_optical_params.rs");
    }

    let crystal_out = out_dir.join("generated_crystal_tables.rs");
    if !crystal_out.exists() {
        fs::write(
            &crystal_out,
            "// generated_crystal_tables.rs -- placeholder (Phase 4 / task #58 pending)\n",
        )
        .expect("failed to write generated_crystal_tables.rs");
    }
}

/// Read a CSV with header `energy_ev,n,k` and return (ev, n, k) tuples.
fn read_nk_csv(path: &PathBuf) -> Vec<(f64, f64, f64)> {
    let f = File::open(path).unwrap_or_else(|e| panic!("cannot open {path:?}: {e}"));
    let reader = BufReader::new(f);
    let mut rows = Vec::new();
    for (i, line) in reader.lines().enumerate() {
        let line = line.expect("io error reading csv");
        if i == 0 {
            continue; // skip header
        }
        let parts: Vec<&str> = line.splitn(3, ',').collect();
        assert_eq!(
            parts.len(),
            3,
            "malformed CSV row {i} in {path:?}: {line:?}"
        );
        let ev: f64 = parts[0].parse().unwrap_or_else(|e| {
            panic!("bad energy_ev at row {i} in {path:?}: {e}")
        });
        let n: f64 = parts[1].parse().unwrap_or_else(|e| {
            panic!("bad n at row {i} in {path:?}: {e}")
        });
        let k: f64 = parts[2].parse().unwrap_or_else(|e| {
            panic!("bad k at row {i} in {path:?}: {e}")
        });
        rows.push((ev, n, k));
    }
    rows
}

/// Write `pub const NAME: [f64; N] = [...];` to the output file.
/// Prefixed with `#[allow(dead_code)]` so warnings-as-errors does not fire
/// during the migration phase before materials_core is wired in.
fn emit_f64_const(
    out: &mut File,
    name: &str,
    n: usize,
    values: impl Iterator<Item = f64>,
) {
    writeln!(out, "#[allow(dead_code)]").unwrap();
    write!(out, "pub const {name}: [f64; {n}] = [\n    ").unwrap();
    let vals: Vec<f64> = values.collect();
    for (i, v) in vals.iter().enumerate() {
        if i > 0 && i % 9 == 0 {
            write!(out, "\n    ").unwrap();
        }
        write!(out, "{v:?}, ").unwrap();
    }
    writeln!(out, "\n];").unwrap();
}
