// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED BY /init: POINTER STUB -->
//! <!-- Source of truth: agents.toml -->
//!
//! # CLAUDE Stub
//!
//! Use `agents.toml` as the canonical cross-agent source.
//! Read sections:
//! - `shared`
//! - `agents.claude`
//!
//! Apply Claude-specific notes only as additive overlays to shared policy.
//!
