// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260214_121216_workspace_root_docs_first_party_filetype_harmonization_playbook.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Filetype Harmonization Playbook
//!
//! ## Scope
//! Harmonize like-for-like artifacts across the workspace by file class:
//! - `.md` documentation,
//! - `.py` Python tooling,
//! - `.sh` shell orchestration.
//!
//! ## Method
//! 1. Measure each file class:
//! >  - count,
//! >  - total lines,
//! >  - TODO/FIXME density,
//! >  - duplicate basenames.
//! 2. Identify collision clusters by basename and path role.
//! 3. Apply class-specific synthesis rules.
//! 4. Re-run policy gate and publish updated evidence.
//!
//! ## Class-Specific Rules
//!
//! ### Markdown (`.md`)
//! - Preserve provenance snapshots in module boundaries.
//! - Consolidate navigation with first-party indices.
//! - Archive exact duplicates with hash logs.
//! - Reconcile conflicting claims into first-party constitutional/spec documents.
//!
//! ### Python (`.py`)
//! - Enforce multithreading/parallel policy or explicit exemptions.
//! > - Prioritize high-impact IO/tooling scripts for concurrency refactors.
//! - Keep tests and package markers exempt only when justified.
//!
//! ### Shell (`.sh`)
//! - Keep scripts deterministic, timestamped, and artifact-producing.
//! - Compose operations through gate orchestration rather than manual sequences.
//! - Favor idempotent behavior and machine-readable outputs.
//!
//! ## Automated Evidence
//! - Analyzer script: `scripts/analyze_filetype_harmonization.sh`
//! - Legacy summary/duplicate snapshots are archived under:
//! - `docs/archive/legacy_unified_docs/LATEST.md`
//! - Current singular duplicate evidence is emitted per run:
//! - `logs/singular_structure_duplicates_<TS>.tsv`
//! - `logs/singular_structure_dedupe_actions_<TS>.tsv`
//!
//! ## Outcome Objective
//! Transform file-class chaos into a governed synthesis system where each class has:
//! - measurable state,
//! - explicit merge/archive policy,
//! - automated verification path.
//!
