// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260214_121216_workspace_root_docs_consolidation_conflict_resolution.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Archived Legacy Document
//!
//! This document was archived as part of singular-lane cleanup.
//!
//! - archived_at: 20260213_221719
//! - archived_path: docs/archive/legacy_unified_docs/20260213_221719/docs/CONSOLIDATION_CONFLICT_RESOLUTION.md
//! - sha256: aa71a6841749192e6b3896a9f347a04ab0d089c4e7eb2501385b55f44ab9460e
//! - rationale: legacy_unified_lane_artifact_replaced_by_singular_repo_structure
//!
//! For active structure and operations, use:
//! - `docs/SINGULAR_REPO_LAYOUT.md`
//! - `docs/MERGE_IN_WORKFLOW.md`
//! - `docs/LEGACY_LANE_RETIREMENT.md`
//!
