//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260214_121216_workspace_root_docs_sync_scope_from_source_folders.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Sync Scope From Source Folders
//!
//! ## Purpose
//! Define exactly what is synchronized in the singular repository now that root modules are authoritative.
//!
//! ## Two-level sync map
//! ```ignore
//! root authoritative modules/
//! |-- research/
//! |   |-- active: docs/, implementations/, tests/, scripts/, requirements.md, README.md
//! |   `-- excluded from reconciler: .git/, .github/, venv/, .venv/, target/, build/, caches
//! |-- experiments/
//! |   |-- active: src/, tests/, pyproject.toml, requirements.md, README.md
//! |   `-- excluded from reconciler: .git/, .github/, node_modules/, venv/, .venv/, build/, dist/, caches
//! `-- learner/
//! >   |-- active: components/, logic/, services/, package.json, requirements.md, README.md
//! >   `-- excluded from reconciler: .git/, .github/, node_modules/, build/, dist/, caches
//!
//! intake lane status/
//! |-- merge_in/README.md
//! `-- archive/intake_lane_retirement/<TS>/merge_in/
//! ```ignore
//!
//! ## Root canonical files regenerated every singular reconciliation pass
//! - `.gitignore`
//! - `README.md`
//! - `LICENSE`
//! - `requirements.md`
//!
//! ## Duplicate reconciliation policy
//! - Intra-module exact duplicates: secondary files become symlinks to module-local canonical file.
//! - Cross-module `LICENSE` duplicates: module copies become symlinks to root `LICENSE`.
//! - Cross-module empty placeholders: logged as `skipped_cross_module_empty`.
//! - Other cross-module duplicates: logged as `skipped_cross_module` and kept module-scoped.
//!
//! ## Evidence outputs
//! - `logs/singular_structure_merge_<TS>.md`
//! - `logs/singular_structure_manifest_<TS>.tsv`
//! - `logs/singular_structure_conflicts_<TS>.tsv`
//! - `logs/singular_structure_dedupe_actions_<TS>.tsv`
//! - `logs/singular_structure_duplicates_<TS>.tsv`
//!
