// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260214_121216_workspace_root_docs_module_file_consolidation_rules.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Archived Legacy Document
//!
//! This document was archived as part of singular-lane cleanup.
//!
//! - archived_at: 20260213_221719
//! - archived_path: docs/archive/legacy_unified_docs/20260213_221719/docs/MODULE_FILE_CONSOLIDATION_RULES.md
//! - sha256: 79477310b41a16fc1d113f1e94ca50db8036d0249eede5b07911fab8bae97c6a
//! - rationale: legacy_unified_lane_artifact_replaced_by_singular_repo_structure
//!
//! For active structure and operations, use:
//! - `docs/SINGULAR_REPO_LAYOUT.md`
//! - `docs/MERGE_IN_WORKFLOW.md`
//! - `docs/LEGACY_LANE_RETIREMENT.md`
//!
