//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260214_121216_workspace_root_docs_ascii_communication_style.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # ASCII-First Communication Style
//!
//! ## Purpose
//! Keep user updates visual, low-text, and easy to scan during merge, dedupe, and reconciliation work.
//!
//! ## Default format
//! 1. One-line status.
//! 2. ASCII diagram first.
//! 3. Short facts block (counts, conflicts, evidence files).
//! 4. Optional next actions as numbered choices.
//!
//! ## Constraints
//! - Use ASCII characters only in diagrams.
//! - Default diagram depth is two levels unless the user asks for more.
//! - Prefer exact paths and explicit timestamps.
//! - Keep prose short and avoid dense paragraphs.
//!
//! ## Reusable template
//! ```ignore
//! Status: <one sentence>
//!
//! <ASCII diagram>
//!
//! Snapshot:
//! - Timestamp: <YYYY-MM-DD HH:MM:SS>
//! - Counts: <module facts>
//! - Conflicts: <short list>
//! - Evidence: <path1>, <path2>
//!
//! Next options:
//! 1. <option A>
//! 2. <option B>
//! ```ignore
//!
//! ## Singular project mapping reminder
//! - Active sources: `research/`, `experiments/`, `learner/`
//! - Retired intake snapshots: `archive/intake_lane_retirement/<TS>/merge_in/*`
//! - Targets: `research/`, `experiments/`, `learner/`
//! - Detailed sync scope map: `docs/SYNC_SCOPE_FROM_SOURCE_FOLDERS.md`
//!
