// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED: DO NOT EDIT -->
//! <!-- Source of truth: registry/entrypoint_docs.toml -->
//!
//! # README
//!
//! (No body_markdown captured in registry/entrypoint_docs.toml.)
//!
