// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_batches_sedenions_addenda_unresolved_direct_sources.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Unresolved Direct Sources (2026-02-15)
//!
//! 1. `https://core.ac.uk/download/pdf/82141950.pdf`
//! - Status from this environment: `404` (and alternate attempts returned `503`/unavailable).
//! - Local placeholder path:
//! - `data/external/sedenions_addenda/files/openpdf/core-cd/82141950-08bda771.pdf`
//!
//! If you find a valid PDF for this exact paper, share the local file path and I will replace the placeholder immediately.
//!
