//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260214_121216_workspace_root_docs_archive_legacy_unified_docs_latest.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Legacy Unified Docs Archive Pointer
//!
//! - latest_archive: docs/archive/legacy_unified_docs/20260213_221719
//! - report: logs/legacy_docs_archive_20260213_221719.md
//! - table: logs/legacy_docs_archive_20260213_221719.tsv
//! - archived_docs: 8
//! - stubbed_markdown_files: 3
//! - skipped_missing_files: 0
//!
