//! <!-- AUTO-GENERATED BY markdown_to_rust: DO NOT EDIT -->
//! <!-- Source: static mirror converted from docs/data markdown; see git log for data_papers_intake_2026_02_15_cayley_dickson_sources_supplemental_docs_lambda_core_documents_primary_lambda_gororoba_backups_20260213_163149_workspace_root_docs_first_party_unified_repo_constitution.rs -->
//! <!-- Regenerate: cargo run --release -p gororoba_cli_data --bin markdown_to_rust -->
//!
//! # Unified Repo Constitution
//!
//! ## Mission
//! Build `lambda_gororoba` as a unified, reproducible, multi-module lambda research system that preserves source provenance while creating new first-party scientific and engineering value.
//!
//! ## Principles
//! 1. Non-destructive integration.
//! 2. Root workspace as source of truth.
//! 3. `merge_in/` as deterministic intake lane.
//! 4. Evidence-first decisions with timestamped artifacts.
//! 5. Module boundaries preserved unless explicitly re-specified.
//! 6. Legal and installation metadata remain module-canonical.
//! 7. Warning findings are treated as blocking risks.
//!
//! ## Constitutional Layers
//! - Layer 1: intake repositories (`merge_in/*`).
//! - Layer 2: unified module snapshots (`src/lambda_unified/modules/*`).
//! - Layer 3: first-party synthesis (`docs/first_party/*`, root governance, and orchestrator scripts).
//!
//! ## Governance Invariants
//! - Every deterministic process writes a timestamped artifact under `logs/`.
//! - Every archive move must be hash-verified and reversible.
//! - Every policy must have an automated verifier when feasible.
//! - Every unresolved conflict must be recorded with owner, action, and evidence.
//!
//! ## Scientific Position
//! The repository is treated as a composite research instrument:
//! - documentation corpus,
//! - experiment corpus,
//! - verification corpus,
//! - integration corpus.
//!
//! Synthesis is additive: knowledge is transformed and reconciled, not discarded.
//!
