// @generated by registry-emit; do not edit. Source: registry/canonical/control_plane.sqlite3
//! <!-- AUTO-GENERATED: DO NOT EDIT -->
//! <!-- Source of truth: registry/claims_domains.toml -->
//!
//! # Claims: rocq
//!
//! Count: 0
//!
