//! Extended binary Golay code `\[24, 12, 8]`.
//!
//! The extended binary Golay code `C_24` is a `\[24,12,8]` self-dual binary code.
//! It has 4096 codewords, minimum Hamming distance 8, and is unique up to
//! equivalence. It is the foundation for constructing the Leech lattice
//! via Construction A.
//!
//! # Construction
//! Generator matrix G = `[I_12 | P]` in systematic form, where P is the
//! 12x12 binary matrix from Conway & Sloane, "Sphere Packings, Lattices
//! and Groups", Chapter 2, Table 2.6.

/// The P matrix for the extended `\[24,12,8]` Golay code in systematic form.
/// G = `[I_12 | P]`. Each row of P is a 12-bit binary vector.
///
/// This is the standard form where the first 12 columns are the identity
/// and the last 12 columns are this matrix.
///
/// Source: Conway & Sloane Ch. 2; equivalent to the Paley construction
/// from the quadratic residues mod 11 plus a border of all-ones.
pub const GOLAY_P_MATRIX: [[u8; 12]; 12] = [
    [1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
    [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
    [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
    [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
    [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
    [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
    [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
    [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
    [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
];

/// Generate all 4096 codewords of the extended Golay code.
///
/// Each codeword is a 24-element binary vector (u8 values 0 or 1).
/// The code is generated by all 2^12 = 4096 linear combinations of the
/// 12 rows of G = `[I_12 | P]` over GF(2).
pub fn golay_codewords() -> Vec<[u8; 24]> {
    let mut codewords = Vec::with_capacity(4096);

    for bits in 0u16..4096 {
        let mut word = [0u8; 24];

        // For each active bit in the 12-bit selector, XOR the corresponding
        // row of G = [I_12 | P]
        for row in 0..12 {
            if (bits >> row) & 1 == 1 {
                // Identity part: bit `row` in first 12 positions
                word[row] ^= 1;
                // P matrix part: last 12 positions
                for col in 0..12 {
                    word[12 + col] ^= GOLAY_P_MATRIX[row][col];
                }
            }
        }

        codewords.push(word);
    }

    codewords
}

/// Check if a 24-bit binary vector is a Golay codeword.
///
/// Uses syndrome decoding: compute w * G^T mod 2. If the syndrome is zero,
/// the word is a codeword. For the systematic form, the syndrome is
/// w`[12..24]` + w`[0..12]` * P mod 2.
pub fn is_golay_codeword(word: &[u8; 24]) -> bool {
    for row in 0..12 {
        let mut syndrome_bit: u8 = word[12 + row];
        for col in 0..12 {
            syndrome_bit ^= word[col] * GOLAY_P_MATRIX[col][row];
        }
        if !syndrome_bit.is_multiple_of(2) {
            return false;
        }
    }
    true
}

/// Compute the Hamming weight (number of 1s) of a 24-bit binary vector.
pub fn hamming_weight(word: &[u8; 24]) -> usize {
    word.iter().map(|&b| b as usize).sum()
}

/// Compute the minimum Hamming distance of the Golay code.
///
/// For the extended Golay code this is exactly 8. This function verifies
/// the property by exhaustive check over all nonzero codewords.
pub fn minimum_distance() -> usize {
    let codewords = golay_codewords();
    let mut min_wt = 25;
    for cw in &codewords {
        let wt = hamming_weight(cw);
        if wt > 0 && wt < min_wt {
            min_wt = wt;
        }
    }
    min_wt
}

/// Weight enumerator: count codewords of each Hamming weight.
///
/// Returns a vector indexed by weight (0..=24). For the extended Golay code:
/// A_0 = 1, A_8 = 759, A_12 = 2576, A_16 = 759, A_24 = 1.
pub fn weight_enumerator() -> Vec<usize> {
    let codewords = golay_codewords();
    let mut counts = vec![0usize; 25];
    for cw in &codewords {
        counts[hamming_weight(cw)] += 1;
    }
    counts
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_golay_codeword_count() {
        assert_eq!(golay_codewords().len(), 4096);
    }

    #[test]
    fn test_golay_minimum_distance() {
        assert_eq!(minimum_distance(), 8);
    }

    #[test]
    fn test_golay_zero_codeword() {
        let codewords = golay_codewords();
        assert_eq!(codewords[0], [0u8; 24], "First codeword should be all-zero");
    }

    #[test]
    fn test_golay_all_codewords_valid() {
        let codewords = golay_codewords();
        for (i, cw) in codewords.iter().enumerate() {
            assert!(
                is_golay_codeword(cw),
                "Codeword {} should pass syndrome check",
                i
            );
        }
    }

    #[test]
    fn test_golay_non_codeword() {
        let mut word = [0u8; 24];
        word[0] = 1; // Single bit set -- Hamming weight 1, not a codeword (d_min=8)
        assert!(!is_golay_codeword(&word));
    }

    #[test]
    fn test_golay_weight_enumerator() {
        let we = weight_enumerator();
        assert_eq!(we[0], 1, "A_0 = 1 (zero codeword)");
        assert_eq!(we[8], 759, "A_8 = 759 (octads)");
        assert_eq!(we[12], 2576, "A_12 = 2576 (dodecads)");
        assert_eq!(we[16], 759, "A_16 = 759 (complements of octads)");
        assert_eq!(we[24], 1, "A_24 = 1 (all-ones codeword)");
        let total: usize = we.iter().sum();
        assert_eq!(total, 4096, "Total codewords = 2^12 = 4096");
    }

    #[test]
    fn test_golay_self_dual() {
        // The extended Golay code is self-dual: G * G^T = 0 mod 2.
        // For systematic form, this means P * P^T = I mod 2.
        // Actually for the extended code: P * P^T + I = 0 mod 2, i.e. P * P^T = I mod 2.
        for (i, row_i) in GOLAY_P_MATRIX.iter().enumerate() {
            for (j, row_j) in GOLAY_P_MATRIX.iter().enumerate() {
                let mut dot: u8 = 0;
                for (ri, rj) in row_i.iter().zip(row_j.iter()) {
                    dot ^= ri & rj;
                }
                let expected = if i == j { 1 } else { 0 };
                // For self-dual: (I + P*P^T) = 0 mod 2, so P*P^T = I mod 2
                assert_eq!(
                    dot % 2,
                    expected,
                    "P*P^T[{},{}] = {} mod 2, expected {}",
                    i,
                    j,
                    dot % 2,
                    expected
                );
            }
        }
    }
}
